### ISSUE TITLE
Hellscream's Fist

### ISSUE THREAD

**Issue by TheRealRickle** [Damieninabox/Lotus-WoW-Bugtracker#101]
**Describe the bug**
The ship Hellscream's Fist doesn't move at all

**To Reproduce**
Find Hellscream's Fist and you'll see it's stationary

Location
East of Orgrimmar in the air

Name, Type

Problem Description

How it should work
The ship should fly around, unsure about the exact path but it shouldn't be stationary at least.

**Comment by Damieninabox** [comment]
Really?

Any source that confirms it?

I've never seen it flying around, couldn't think about it on retail neither

**Comment by TheRealRickle** [comment]
I remember it flying around back then, having to look for it, but I have no idea about the path, I'll try to find a source that can confirm it

**Comment by TheRealRickle** [comment]
> Really?
> 
> Any source that confirms it?
> 
> I've never seen it flying around, couldn't think about it on retail neither

You're absolutely correct, my memory was incorrect, it's supposed to be stationary
