### ISSUE TITLE
Glyph | Regrowth

### ISSUE THREAD

**Issue by Anakia69** [Damieninabox/Lotus-WoW-Bugtracker#103]
_**Describe the bug**_

The Glyph of Regrowth doesn't seem to be working.

_**To Reproduce**_

Use the glyph, cast regrowth and see that you do not always crit with it.

_**Screenshots**_

N/C

_**Additional context**_

"Regrowth has a 60% increased chance for a critical effect". Combined with the glyph, the spell should always crit. It doesn't. 

Some druid guides also mention the fact that since regrowth should always crit (with that glyph), the spell should therefore replace Healing Touch (that is just to illustrate the fact that it should always crit).

**Comment by Damieninabox** [comment]
Fixed with next core update -> it worked correct before, someone reported it was bugged, reverted the code to its initial state (it always worked properly, we basically bugged it out)...
