### ISSUE TITLE
[NPC] Stonebull Crayfish

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#105]
**Describe the bug**
Creature is unable to be found in its corresponding subzones and seemingly lacks entries in both world placements and in the loot tables for Stonebull Lake, rendering the fishing daily quest 'Craving Crayfish' unable to be completed.

https://www.wowhead.com/npc=53561/stonebull-crayfish
https://www.wowhead.com/item=69977/stonebull-crayfish
Stonebull Lake ZoneID: 223

Kind regards,

**Comment by Damieninabox** [comment]
Fixed with next restart
