### ISSUE TITLE
Mogushanpalace trashmob dmg

### ISSUE THREAD

**Issue by Yurikanta** [Damieninabox/Lotus-WoW-Bugtracker#107]
**Describe the bug**
Meleehit damage from trashmobs inside Mogushanpalace on NHC is way too low

**To Reproduce**
move in the dungeon and get hit by random trash mobs

Location
Mogu'shan Palace dungeon nhc

Problem Description
700dmg per meleehit instead of 10-12k

**Screenshots**
![image](https://user-images.githubusercontent.com/82386008/144752786-72bb2d8c-ce85-4304-a8c0-efd58ed2b95d.png)

**Additional context**
Tank POV retail
https://www.youtube.com/watch?v=z4rlK8cY-m8&ab_channel=WarriorTSW

**Comment by Damieninabox** [comment]
Fixed with next server restart.
