### ISSUE TITLE
Dungeon | Scarlet Monastery HC | Normal loot

### ISSUE THREAD

**Issue by hamyhamz** [Damieninabox/Lotus-WoW-Bugtracker#108]
We have cleared Scarlet Monastery Heroic dungeon with a group of plp and last boss (High Inquisitor Whitemane) dropped a piece of normal loot, along with 2 pieces of heroic loot from another boss. See screenshots attached. Not sure whether the two pieces are normal for this dungeon or not, but the normal drop certainly is not. 

**To Reproduce**
Scarlet Monastery Heroic (Last boss|
High Inquisitor Whitemane dropped a "Whitemane's Chapeau" cloth helmet. 
Normal loot should not be dropping in heroic version of the dungeon.
I tried finding a source for the loot that drops, or any other comment on wowhead and also watched multiple videos on people killing her (e.g. https://www.youtube.com/watch?v=PejDostbjZw) and everywhere there were two heroic items that dropped and no normal loot.

**Screenshots**
![image](https://user-images.githubusercontent.com/30901696/144754996-ec4b6f09-c1bc-4bf8-be82-280ed0f5c09f.png)
![image](https://user-images.githubusercontent.com/30901696/144755014-39a3435a-7411-4d9c-ba22-fafc903ad5b7.png)

**Additional context**
None

**Comment by Damieninabox** [comment]
Fixed with next server restart
