### ISSUE TITLE
legendary chain starting chain quest

### ISSUE THREAD

**Issue by vertria** [Damieninabox/Lotus-WoW-Bugtracker#11]
quest name :Stranger in a Strange Land
no quest picker there
![WoWScrnShot_120321_231125](https://user-images.githubusercontent.com/88947171/144667085-4b8bccdb-71de-4c19-a4b5-129ee5c73ef6.jpg)
.

**Comment by vertria** [comment]
still duplicated quest

**Comment by BanHammer69** [comment]
Since it's already reported adding my detection here too. Quest is duplicated and obviously Wrathion isn't scripted

https://www.wowhead.com/quest=31488/stranger-in-a-strange-land

![Wrathion Bug](https://user-images.githubusercontent.com/95563818/144747694-ef4caeea-370e-4dfa-b745-e21cdabb3ce1.PNG)
