### ISSUE TITLE
[QUEST] We're Here to Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#110]
**Describe the bug**
Quest behaves inconveniently as players are unable to enter the Krom'gar Wagon stationed in Silverwind Refuge, informing the player they are in the wrong zone, rendering them unable to attain the Krom'gar Grunt effect in Stonetalon Mountains.

**To Reproduce**
Steps to reproduce the behavior: Attempt to enter the Krom'gar Wagon.
Location: Silverwind Refuge
Krom'gar Wagon
How it should work: Despite the quest text behaving as complete, riding the Krom'gar Wagon is essential for quest credit.

**Additional context**
https://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two
https://www.wowhead.com/npc=41744/kromgar-wagon

Kind regards,

**Comment by Damieninabox** [comment]
Fixed with next update
