### ISSUE TITLE
[Quest] Only the Worthy Shall Pass (Pandaren Starting Zone)

### ISSUE THREAD

**Issue by Adaraas** [Damieninabox/Lotus-WoW-Bugtracker#111]
**Describe the bug**
While attempting to do this quest, I've gotten to the stage where you must defeat Master Li Fei after lightning all the braziers, and he just starts there. No way to interract or attack him.

**To Reproduce**
Shrine of Inner Light is the zone name. To reproduce just start the quest.

**Comment by Damieninabox** [comment]
Fixed some time ago, can't find the issue (for w/e reason)
