### ISSUE TITLE
[Object] Coiled Rope (Southern Barrens)

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#112]
**Describe the bug**
These two entries of the interactive object should serve as a shortcut to get back up on the mountains behind Honor's Stand in Southerns. Currently, they do nothing.

https://www.wowhead.com/object=201707/coiled-rope#same-model-as

**To Reproduce**
Steps to reproduce the behavior: Use either of the Coiled Rope objects as a horde player. Neither of them will not work.
Location: Southern Barrens

**Screenshots**
![image](https://user-images.githubusercontent.com/6233159/144757142-0f39f76f-d333-4672-ae02-7b91e6f75989.png)

Kind regards,

**Comment by Damieninabox** [comment]
Fixed with next restart
