### ISSUE TITLE
NPC -Kor'vess mob aggro issues 

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#113]
**Describe the bug**
Some NPCs do not attack/aggro

Some Battlesingers need to figure out their weirdness. I Deaggro'd them then they reaggro'd when I appeared within a 100+ yrd radius***This one will need to be tested further.

**To Reproduce**
Stand near mobs/attack them
Location Dread Wastes - Kor'vess

How it should work
They should be aggressive and aggro within their determined radius. 
They should attack back when attacked 

Due to time constraints and lag I will update for more NPCs later. If any coupled SS look like they're from different mobs just let me know.

**Screenshots**
This NPC does not aggro
![WoWScrnShot_120521_113220](https://user-images.githubusercontent.com/95519949/144756999-112837d4-ac99-473c-8daf-d7c2bab3914a.jpg)
![WoWScrnShot_120521_113232](https://user-images.githubusercontent.com/95519949/144757043-64154f20-20f9-4c0d-92f1-24d14c682657.jpg)

NPCs in this chamber do not attack even when attacked
![WoWScrnShot_120521_114348](https://user-images.githubusercontent.com/95519949/144757347-db32821c-1874-4bac-89b3-880a7e7b790c.jpg)
![WoWScrnShot_120521_114350](https://user-images.githubusercontent.com/95519949/144757357-468a7761-c33a-4df2-aa1f-ff5beee081e1.jpg)

These NPCs do not aggro or attack when attacked back
![WoWScrnShot_120521_114523](https://user-images.githubusercontent.com/95519949/144757395-f358165b-8e68-49c8-b778-718ff56e0e28.jpg)
![WoWScrnShot_120521_114526](https://user-images.githubusercontent.com/95519949/144757400-0b62d7af-ed07-481a-89b5-2dbfd4abe83a.jpg)

There is a battle singer here but they aggro and attack fine
![WoWScrnShot_120521_115001](https://user-images.githubusercontent.com/95519949/144757549-c291f2db-37ba-42ef-9fff-5a0f18194fb9.jpg)
![WoWScrnShot_120521_115005](https://user-images.githubusercontent.com/95519949/144757561-a55fee7d-3598-4ef9-a838-a66fbb3ba29e.jpg)

Does not attack/aggro - believe he may need to also be in a different idle stance rather than a passive.
![WoWScrnShot_120521_115435](https://user-images.githubusercontent.com/95519949/144757677-bf650052-42df-4cdf-b03f-7d38752260c3.jpg)
![WoWScrnShot_120521_115437](https://user-images.githubusercontent.com/95519949/144757688-b840f0f2-7bba-44d6-b794-3e055b363f1c.jpg)

NPCs on left will aggro , that is not their orignal starting positions. The havoc (furthest left) is still aggro'd though and will attack when you're near - sometimes moves if he feels like it. 
Havoc on the right does not aggro but attacks back
![WoWScrnShot_120521_115907](https://user-images.githubusercontent.com/95519949/144757864-aabe030c-aacf-4860-973d-e16bdfb0205f.jpg)
![WoWScrnShot_120521_115908](https://user-images.githubusercontent.com/95519949/144757872-6ff78d67-e014-42a0-b5fd-d01872935845.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server restart
