### ISSUE TITLE
[QUEST] Desolation Hold Inspection

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#118]
**Describe the bug**
The gossip options are missing on both Warlord Bloodhilt and Warlord Gar'dul, rendering players unable to progress the quest further, while also not being able to assure themselves safe passage to Desolation Hold.

https://www.wowhead.com/quest=24577/desolation-hold-inspection
https://www.wowhead.com/npc=37679/warlord-bloodhilt
https://www.wowhead.com/npc=37811/warlord-gardul

How it should work: https://www.youtube.com/watch?v=RrD0gD0GMGk

Kind regards,

**Comment by Damieninabox** [comment]
Fixed with next server update
