### ISSUE TITLE
Raid - MsV | Gara'jal + Spirit Kings + Elegon + WoE

### ISSUE THREAD

**Issue by Anakia69** [Damieninabox/Lotus-WoW-Bugtracker#123]
_**Describe the bug**_

Gara'jal : dolls targetting both healers, I don't think this should ever happen

Spirit kings : MC spell feels kinda meh, displaying allies as ennemies even after the spell is broken

Elegon : 
=> boss not centered on his platform
=> boss respawning under his platform after a wipe
=> pylons facing the wrong way
=> trigger area of celestial form is too big I guess since it triggers the form even far outside the platform, causing issues for both players and adds to destack

WoE : 
=> Emperor's courage : their aggro resets and they do not focus the right targets (they should only focus tanks and walk towards them, atm they focus based on player's threat)
=> Emperor's rage : the npc also works by threat
=> Jan-xi & Qin-xi : their "dance" are kinda meh aswell, someting we get hit by their abilities while visually not being in the area displayed on the floor
=> Opportunistic strike sometimes after dodging only 2 combos, sometimes not usable, it also feels like the extra button sometimes disappears too quickly (should be 3s)

_**To Reproduce**_

I guess you have to test each boss ehe

_**Screenshots**_

see https://www.twitch.tv/videos/1225128915 (arms warrior pov)
see https://www.twitch.tv/videos/1225119667 (monk tank pov)

_**Additional context**_

N/C. I'd like to apologize, I should probably create a post for each boss but it's kinda late and I have to wake up early tomorrow. Chose to report it all in one single post.

if any question arises : ! <DXE™> Malax on Lotus Discord. Guild ig : Eternal Symphonia. Char name : Bringbackdxe

**Comment by Damieninabox** [comment]
@Greymane to reproduce the wipe issue, make sure to die properly against the boss, release spirit, go back in and once it loads his Grid, he will fall under the map

For Gajal, also check line 63 to 80, spells getting applied, their effects are non working, which will make healers go oom, also dps losing dps because of non working effects

**Comment by Greymane** [comment]
@Anakia69 Some issues i wasn't abe to reproduce:

> boss not centered on his platform.

He didn't leave his spot once.

> trigger area of celestial form is too big I guess since it triggers the form even far outside the platform, causing issues for both players and adds to destack.

Seems fine to me, [outside](https://puu.sh/IzRy7/07fa9ab98d.jpg) and [inside](https://puu.sh/IzRyG/91b4360a64.jpg)

> Jan-xi & Qin-xi : their "dance" are kinda meh aswell, someting we get hit by their abilities while visually not being in the area displayed on the floor.

> Opportunistic strike sometimes after dodging only 2 combos, sometimes not usable, it also feels like the extra button sometimes disappears too quickly (should be 3s).

These last two i would say were mostly caused by the server lags/freezes we used to have.

**Comment by Anakia69** [comment]
@Greymane 
check https://www.twitch.tv/videos/1225128915?t=1h7m22s
I don't know if the position of the boss has been fixed, but as you can see on my vod he's not centered on his platform. You can also witness issues with the "astral form" in the next few seconds of the vod.

**Comment by Greymane** [comment]
Yeah, another issue caused by his mispositioning, both the platform Buff and the Radiating Energies misposition. It was probably caused by his fall from the platform, which is now fixed. If it ever happen again, please open a new report.
