### ISSUE TITLE
[Dungeon] The Slave Pens (nhc)

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#124]
Coilfang Scale-Healer (21126):
starting to cast Heal (34945) but stops and stays at 0.1 sec.

Naturalist Bite (17893):
Not moving out of prison

Quest: The Heart of the Matter (29565)
Both Objectives are missing: 
The Invader's Claw (72118)
The Slave Master's Eye (72119)

**Comment by Damieninabox** [comment]
Fixed with next server update
