### ISSUE TITLE
[Dungeon] Auchenai Crypts (nhc)

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#126]
Exarch Maladaar (18373)
dropping hc loot in nhc

Quest: Raging Spirits (29591)
There are not enough Raging Skeleton (18521) to complete the Quest. Should be 6.

**Comment by Damieninabox** [comment]
Fixed Raging Skeleton spawns, could not reproduce Exarch Maladaar dropping hc loot in nhc, if you however encounter it, make sure to write down the correct name AND OR the proper ID of the item. Thanks
