### ISSUE TITLE
[Dungeon] Sethekk Halls (nhc)

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#127]
Quest: Eyes of Desire (29607)
Cobalt Eye (72480) not dropping from Cobalt Serpent (19428)

Old and New Quest NPC can be found outside and inside of Auchindoun. 
Therefore you can get both, the old version and new version of the same quests.
When looting old and new Questitems, the completing of Quests gets messed up.

**Comment by Damieninabox** [comment]
Fixed with next server restart
