### ISSUE TITLE
[RAID] MsV Gara'Jal the Spiritbinder

### ISSUE THREAD

**Issue by Krysh11** [Damieninabox/Lotus-WoW-Bugtracker#129]
The bug:
When healers go into the spirit world heal players and leave they get the buff Spiritual Innervation, but this buff does not actually cause the healer to regenerate a significant amount of mana.

Mogu'shan Vaults
Gara'jal the Spiritbinder, Mob
Spiritual Innervation buff does not cause buff recipient to regenerate a significant amount of mana.
When healers get the Spiritual Innervation buff they are supposed to regenerate a bunch of mana.

**Comment by TornroosV** [comment]
The tooltip for Mistweaver monk read Gain 0 chi every 1 second. as you can see in the clip below.
https://clips.twitch.tv/SmoothFunnyKiwiPermaSmug-8pkwfWJCSIsu_mQd

**Comment by Damieninabox** [comment]
Already fixed on the live server
