### ISSUE TITLE
Spell I Faerie Swarm talent is kinda OP

### ISSUE THREAD

**Issue by Missix12** [Damieninabox/Lotus-WoW-Bugtracker#13]
Faerie Swarm talent for druid is op, slow effect lasts for 5 min on pve and 20 sec for pvp targets.
![ddddddd](https://user-images.githubusercontent.com/95503509/144667472-2ab05891-568f-4d37-bf2d-1838fb922d4d.png)
Should work like that screenshot says, 15 sec on pve and idk 3-5 seconds on pvp?

**Comment by Greymane** [comment]
If you or someone else could provide some proof of that, i believe "CC" effects are supposed to be capped at 10 seconds, maybe faerie fire has a special rule?

**Comment by Greymane** [comment]
Fixed on [e0b2fa7ca56a5c03825fe7804a974e05fb0cb25f](https://github.com/FriendOfTheGrummles/Lotus-WoW-Release/commit/e0b2fa7ca56a5c03825fe7804a974e05fb0cb25f)
