### ISSUE TITLE
Quest: Meet the Scout

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#131]
**Describe the bug**
Unable to see Scout Rokla who is the first objective of this quest (https://www.wowhead.com/quest=32249/meet-the-scout)

**To Reproduce**
Pick up the quest from Sunwalker Dezco in Vale of Eternal Blossoms. 
**Bug** Scout Rokla supposed to be in Krasarang Wilds and her location is shown on minimap but she's not scripted when you get there
**Screenshots**
![Krasarang Bugs](https://user-images.githubusercontent.com/95563818/144795196-00bc4fe7-ed1e-4af2-aaa8-a0903acfe61e.PNG)

**Comment by Damieninabox** [comment]
Currently phased out -> it's 5.1 content which won't be available on launch -> closing this one
