### ISSUE TITLE
Quest: Taking Advantage

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#132]
**Describe the bug**
Purple portal next to the NPC isn't working and hence you cannot continue this quest (https://www.wowhead.com/quest=32118/taking-advantage)

**To Reproduce**
Pick up quest from Belloc Brightblade in Krasarang Wilds. 
There's a purple portal next to her that should tele you to the cave that leads you to the objective NPC **Bug** Portal not working
**Screenshots**
![Krasarang Bugs](https://user-images.githubusercontent.com/95563818/144795593-d7fef5dd-0894-4cf7-b985-b57c635ac6fc.PNG)

**Comment by Damieninabox** [comment]
Fixed with next server restart, won't be available on launch (quest is from 5.1)
