### ISSUE TITLE
NPC - Random Rocket Chicken 

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#138]
**Describe the bug**
Believe it is an event marker but the Rocket Chicken should not appear 

Location - Dread Wastes - Sunset Brewgarden
Name, Type
Problem Description
How it should work

Players shouldn't be able to see him

**Screenshots**
![WoWScrnShot_120621_011733](https://user-images.githubusercontent.com/95519949/144803796-728e77e8-9322-4358-af65-22e7cd095818.jpg)

**Additional context**
https://youtu.be/F0Wk52Ywjz4?t=269)

**Comment by Damieninabox** [comment]
Fixed with next server update
