### ISSUE TITLE
Quest - Once in 100 Life Times

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#139]
**Describe the bug**
Cannot talk to Klaxxi'va and hand in quest 
**To Reproduce**
Location - Dread Wastes - Klaxxi'vess

How it should work
Should be able to hand in quest and accept next one
https://www.youtube.com/watch?v=PCc8aE3oLRw

**Screenshots**
![WoWScrnShot_120621_012302](https://user-images.githubusercontent.com/95519949/144804431-97705bd2-8950-46bd-b8a8-6bdae8e44be4.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server restart, also added proper conditions to NOT start the quest without completing the Dread Wastes storyline achievement "Dread Haste Makes Dread Waste"
