### ISSUE TITLE
Quest | The Source of Our Livelihood

### ISSUE THREAD

**Issue by BottledFart** [Damieninabox/Lotus-WoW-Bugtracker#14]
**Describe the bug**
Quest is completable, but the cart does not work.

**To Reproduce**
Begin the quest, run to the cart, click on it. Quest completes, but you can't ride it.

**Screenshots**
![image](https://user-images.githubusercontent.com/24526201/144668015-42b01c0d-77c7-47c9-b2cf-0c679ce7a468.png)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next restart
