### ISSUE TITLE
"An Ancient Enemy"

### ISSUE THREAD

**Issue by Yurikanta** [Damieninabox/Lotus-WoW-Bugtracker#141]
**Describe the bug**
"An Ancient Enemy" on the Echo Isles not working. The Event starts correctly but once the fight should start nothing happens, which means the quest is not completable

**To Reproduce**
go to the troll starting area and do quests until you reach "An Ancient Enemy"

Location
The Echo Isles

How it should work
the boss should be spawning adds that you have to kill and the NPC would be killing the boss meanwhile

**Screenshots**
![image](https://user-images.githubusercontent.com/82386008/144813543-21ff2849-7114-4c34-b32e-71633e7ae81f.png)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next server update
