### ISSUE TITLE
Brawler's Guild leper gnome quintet fight

### ISSUE THREAD

**Issue by Mx-mp4** [Damieninabox/Lotus-WoW-Bugtracker#144]
**Describe the bug**
In the brawler's guild fight with the Leper gnome quintet at rank 5, when they respawn they all are at 100%hp, on retail wow the leper gnomes have different HP which are: 100%hp, 89%hp, 79%hp, 69%hp and 59%hp

**To Reproduce**
Brawler's guild arena
Reach rank 5 last fight and join the arena talking with a guard
The HP of the elites are different to the HP they have on retail
Each elite has 10% less HP than each other

**Screenshots**

Lotus server: ![WoWScrnShot_120621_123022](https://user-images.githubusercontent.com/95622972/144839857-a727192e-bc01-480d-94c7-872a876ec685.jpg)

The video im watching to complete the brawler's guild: https://www.youtube.com/watch?v=vdAoKaTdXQw  the fight start at 8:49

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next update
