### ISSUE TITLE
Brawler's guild invitation

### ISSUE THREAD

**Issue by Mx-mp4** [Damieninabox/Lotus-WoW-Bugtracker#145]
**Describe the bug**
The item ``Bloodied Scroll´´ ID:93194, that grants u access to the Brawler's guild arena dont works correctly which means that the item should give all the characters of your account (horde or alliance) access to the Brawler's guild arena, but it only gives u access to the faction you have use the item
**To Reproduce**
You can use the item in any place
``Bloodied Scroll´´ ID:93194
Doesnt work like the tooltip of the item say, the item dont give cross-factions access to the Brawler's guild
It should give the access to every char of the account

**Screenshots**
Lotus server with my horde:![WoWScrnShot_120621_131518](https://user-images.githubusercontent.com/95622972/144844933-b1598752-b9c9-43fe-8ac5-75044496ea73.jpg)

Wow-head photo:
![image](https://user-images.githubusercontent.com/95622972/144845119-723fc9aa-6405-4e43-a1b3-7d15ad9d4383.png)

**Additional context**

How it should work

**Screenshots**

**Additional context**

**Comment by Greymane** [comment]
Fixed by editing the achievement Flags in Achivement.DBC, no commit for this one.
