### ISSUE TITLE
[Glyph] Glyph of the Geist

### ISSUE THREAD

**Issue by irrefutable** [Damieninabox/Lotus-WoW-Bugtracker#148]
**Describe the bug**
[Glyph of the Geist ](https://www.wowhead.com/spell=58640/glyph-of-the-geist) transforms https://www.wowhead.com/spell=49206/summon-gargoyle into a geist as well. Should only transform the ghoul.

**To Reproduce**
Apply glyph -> Use garg -> watch it become a geist

**Screenshots**
![image](https://user-images.githubusercontent.com/46446681/144860115-3091532d-05a7-4af4-83a2-a11433ffa88b.png)

**Comment by Damieninabox** [comment]
Fixed on next server update
