### ISSUE TITLE
[Glyph] Glyph of Foul Menagerie

### ISSUE THREAD

**Issue by irrefutable** [Damieninabox/Lotus-WoW-Bugtracker#149]
**Describe the bug**
https://www.wowhead.com/spell=58642/glyph-of-foul-menagerie doesn't apply proper transformation to https://www.wowhead.com/spell=42650/army-of-the-dead .

**To Reproduce**
Apply the Glyph -> Use army of the dead.

**Screenshots**
![image](https://user-images.githubusercontent.com/46446681/144860754-86f09971-51df-407d-a89e-27f890be97e9.png)

**Comment by Damieninabox** [comment]
Fixed with next core update
