### ISSUE TITLE
Dieing on logout whilst in combat

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#151]
Whenever you "Logout" or "Exit Game" while being in combat (for example when hitting dummies in Orgrimmar) your character will die on logout. Probably only an issue in rested zones since you cant just logout in combat outside of rested zones.

Te reproduce i'd suggest you go to any dummy in orgrimmar, autohit it and press logout while doing so. character should be shown as dead in login screen.

**Comment by irrefutable** [comment]
Can confirm that this happened to me multiple times on different characters.

**Comment by Damieninabox** [comment]
Has always been like that, even on retail to this day, closing it for now
