### ISSUE TITLE
Rocket Barrage not scaling properly on AP

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#152]
The goblin racial Rocket Barrage (https://de.wowhead.com/spell=69041/raketenbeschuss) is not scaling right with attackpower, whilst it seems to be fine regarding spellpower. Used it on my rogue and on my priest, screenshots provided below.

To reproduce i'd suggest using an attackpower-based goblin class like rogue and pressing rocket barrage on an enemy.

![WoWScrnShot_120621_154422](https://user-images.githubusercontent.com/95633065/144866319-9716bbd6-d174-443b-bfc5-e3503a6c0ac9.jpg)

![WoWScrnShot_120621_155311](https://user-images.githubusercontent.com/95633065/144867748-e5c3e7fa-7ab1-4d56-9c21-f9fbc2006089.jpg)

**Comment by Greymane** [comment]
@grtandyllw Any ideas on what the proper AP/SP ratio it should have?

**Comment by Damieninabox** [comment]
Fixed with next server update
