### ISSUE TITLE
Treants in Restoration Spec

### ISSUE THREAD

**Issue by Bradeyx** [Damieninabox/Lotus-WoW-Bugtracker#154]
They do not cast Swiftmend. I've tried different ocasions different hots etc.
They will cast healing touch and even then sometimes they will go after the enemy instead of you and when you are injured they will move to you and might cancel the healing touch cast until their duration ends.

**Comment by Damieninabox** [comment]
Tooltip clearly says "Heals a nearby injured ally for xxxx every 2.5 sec AND will use Swiftmend" -> by checking the combat log, you will see that they are healing you with Swiftmend & they are supposed to cast Healing Touch.

Couldn't reproduce the enemy chase
