### ISSUE TITLE
[Spell] Freeze

### ISSUE THREAD

**Issue by irrefutable** [Damieninabox/Lotus-WoW-Bugtracker#156]
**Describe the bug**
https://www.wowhead.com/spell=33395/freeze gives a proc of https://www.wowhead.com/spell=112965/fingers-of-frost even if the target doesn't get rooted (Has windwalk totem applied, Blessing of Freedom and so on).

**To Reproduce**
Duel a shaman or a pally as a frost mage -> use pet nova once they are freedomed with either windwalk or freedom.

**Comment by Damieninabox** [comment]
Fixed with next core update
