### ISSUE TITLE
[NPC] Steelspark LX-506

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#158]
**Describe the bug**
Creature has a way too high damage multiplier for its level (50), effectively able to kill players in one or two hits depending if a critical.

**Screenshots**
![image](https://user-images.githubusercontent.com/6233159/144892143-bfed5630-855a-493b-8220-7b92c26ca816.png)

**Additional context**
Creature is spawned in Gadgetzan through the final quest in the Thunderdrome series: Thunderdrome: Grudge Match!
https://www.wowhead.com/quest=25513/thunderdrome-grudge-match

This issue seems to be recurring for multiple creatures throughout Tanaris, mostly rares.

Kind regards,

**Comment by Damieninabox** [comment]
Fixed with next restart
