### ISSUE TITLE
Quest: Young and Vicious

### ISSUE THREAD

**Issue by Pumpedge** [Damieninabox/Lotus-WoW-Bugtracker#16]
**Describe the bug**
Using quest item results in "invalid target".

**To Reproduce**
Steps to reproduce the behavior: Click the button :)
Location: Blood talon shore, troll starting area
Young and Vicious quest
Problem Description: When using the quest item on the raptor it keeps saying Invalid Target.
How it should work: It should use the item and let me mount the raptor

**Screenshots**
Not applicable.

**Additional context**
Quest is requires to resume the zone. https://www.wowhead.com/quest=24626/young-and-vicious

**Comment by grtandyllw** [comment]
can confirm, same thing happened to me

**Comment by Damieninabox** [comment]
Npc Swiftclaw (entry 38002) works fine -> quest is completable

**Comment by grtandyllw** [comment]
i followed a swiftclaw now and the same "invalid target" happened. 
![WoWScrnShot_121021_000058](https://user-images.githubusercontent.com/95633065/145489449-358a188a-7003-4588-b425-3fbe61f66b1c.jpg)

but there is two swiftclaws. one with blue name, one with green name. only the one with blue name can be mounted, the other one still is an "invalid target"
![WoWScrnShot_121021_000312](https://user-images.githubusercontent.com/95633065/145489603-69354a8b-7d73-4383-a278-44eb8626fb20.jpg)
