### ISSUE TITLE
[Quest] | Much to Learn 

### ISSUE THREAD

**Issue by hamyhamz** [Damieninabox/Lotus-WoW-Bugtracker#162]
There is a typo (wrong tag/syntax) used in this quest. Text <class> is shown in the quest description instead of players actual class. Please refer to the screenshot

![image](https://user-images.githubusercontent.com/30901696/144898916-2b397d85-387f-4952-89ff-7a229e13725c.png)

**Comment by Damieninabox** [comment]
Fixed with next restart. Make sure to fully close your client and delete the "Cache" folder, in order for the fix to show up for the client
