### ISSUE TITLE
[Quest] Vortex

### ISSUE THREAD

**Issue by Yurikanta** [Damieninabox/Lotus-WoW-Bugtracker#165]
**Describe the bug**
You talk to the Elemental that gives you the quest and enter a "vehicle" that flies to the top of the volcano to kill a boss

**To Reproduce**
Just start the quest and you will see that the elemental cant fly and doesnt go its scripted pathway

**Location**
Ashenvale

Problem Description
**How it should work**
The "vehicle" flies up the mountain and you circle the boss. using your special action buttons you kill it and return to the questgiver

**Additional context**
(https://www.youtube.com/watch?v=cWfmfV62zsE&ab_channel=SuperFandeWoW)

**Comment by Damieninabox** [comment]
Fixed with next update
