### ISSUE TITLE
Scarlet Halls; Armsmaster Harlan (stuck after boss is dead)

### ISSUE THREAD

**Issue by Proakten** [Damieninabox/Lotus-WoW-Bugtracker#168]
**Describe the bug**
After defeating Armsmaster Harlan in Scarlet Halls (MoP HC Version, https://www.wowhead.com/npc=58632/armsmaster-harlan) we were stuck and couldnt move. We intentionally went into the Blades of Light ability (https://www.wowhead.com/spell=111216/blades-of-light) and killed the boss during this. Even with the boss dead we couldnt move for 10 to 15 seconds

**To Reproduce**
(didnt try yet)
Go into blades of light and kill the boss during his whirlwind

**Comment by Damieninabox** [comment]
Fixed with next core update
