### ISSUE TITLE
Glyph of Soulstone is not working

### ISSUE THREAD

**Issue by Proakten** [Damieninabox/Lotus-WoW-Bugtracker#171]
**Describe the bug**
When you revive yourself with the soulstone you get revived with 60% HP and not with 100% HP like the glyph would change the spell.
https://wowwiki-archive.fandom.com/wiki/Glyph_of_Soulstone

**To Reproduce**
Apply, Die, Revive

**Additional context**
Tried it with 3 Characters, different Warlock specs, no spec etc. Getting revived with the same % of HP with and without the glyph
(couldnt try it on another person or when the person was already dead)

**Comment by grtandyllw** [comment]
can confirm, glyph of soulstone doesnt do anything.
