### ISSUE TITLE
[Quest] Proving Pit

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#172]
In the quest "Proving Pit"(https://www.wowhead.com/quest=24768/proving-pit), the Captive Spitescale Scout just went back to his cage, after is sent a corruption+shadowbolt at it, having me to ask the Darkspear Jailer to release him again for killing. Worked fine 2nd time around.

**Comment by Damieninabox** [comment]
Could not reproduce it after multiple times of trying it
