### ISSUE TITLE
Kijara's movement 

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#173]
Kijara's (https://de.wowhead.com/npc=37969/kijara) movement looks choppy, sometimes glitching when turning around. Just a cosmetic thing, i think she'd better just stand in place for cosmetic reasons. Also I think i had 2x Questionmark (Quest Indicator) on the Minimap for her when wanting to turn in "https://de.wowhead.com/quest=24622/des-trolls-bester-freund"

**Comment by Damieninabox** [comment]
Adjusted with next restart
