### ISSUE TITLE
[Quest] BEWARE OF CRAGJAW!

### ISSUE THREAD

**Issue by Yurikanta** [Damieninabox/Lotus-WoW-Bugtracker#174]
**Describe the bug**
LvL 27 Elite mob hitting for 1.1k dmg, total overkill

**To Reproduce**
go to the questmob and get hit

**Location**
Stonetalon Mountains

**Problem Description**
He should hit for 200-300 dmg

**Screenshots**
![image](https://user-images.githubusercontent.com/82386008/144989140-105b49e1-a9c7-4972-824a-cbe005e7e6eb.png)

**Additional context**
https://www.youtube.com/watch?v=dnFgInKLlUU&ab_channel=GitGudGuides

**Comment by Damieninabox** [comment]
Fixed with next restart
