### ISSUE TITLE
Focus reset

### ISSUE THREAD

**Issue by HyperionDread** [Damieninabox/Lotus-WoW-Bugtracker#18]
Hunter. Focus resets to 0 when you level up.

It should refill to 100% instead of resetting.

![WoWScrnShot_120321_215318](https://user-images.githubusercontent.com/62250720/144671547-f30a5159-d8a5-49e4-a4a9-cfcee0cc5cd2.jpg)
.
![WoWScrnShot_120321_215349](https://user-images.githubusercontent.com/62250720/144671607-e6eb052d-2aad-436e-be15-9d58f1796ed5.jpg)

**Comment by Greymane** [comment]
This was fixed on f2c07a564f74e096e6ce915408b131bde25b60e0
