### ISSUE TITLE
[Quest] The new you

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#181]
https://www.wowhead.com/quest=14109/the-new-you

Also on that quest, the objective marker on the map doesnt update at all, only showing the location of the first objective (Hip new outfit @szabo) even tho that objective has been long done. relogging doesnt update the marker to the correct location.

![WoWScrnShot_120721_111837](https://user-images.githubusercontent.com/95633065/145011289-88233fee-36b7-4805-941c-a98cfaa3c1aa.jpg)

im not gonna report more bugs where the objective marker doesn't update because this seems to be a general problem for all quests (atlest for quests in the goblin starting zone).

**Comment by Damieninabox** [comment]
It's not an overall issue, I will check the entire zone though
