### ISSUE TITLE
[Quest] Life of the Party

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#182]
https://www.wowhead.com/quest=14153/life-of-the-party

After taking this quest, your action bar changes to the action bar you see in screenshot 1.

Then, when walking away from the questgiver, the actionbar goes back to normal, therefore its impossible to finish the quest (screenshot 2)

![WoWScrnShot_120721_112704](https://user-images.githubusercontent.com/95633065/145012635-181e1166-736d-4199-abcb-9603cff19ed3.jpg)

![WoWScrnShot_120721_112710](https://user-images.githubusercontent.com/95633065/145012643-65734862-e214-42e7-8f94-6ec543764b73.jpg)

**Comment by Damieninabox** [comment]
Fixed with next core update
