### ISSUE TITLE
[Dungeon] Gundrak (nhc)

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#192]
Old and new quests messing up the progress and complete / turning in.

Slad'ran <High Prophet of Sseratus> 29304
Seems to drop hc and nhc loot but could have been an add who dropped. not sure

Eck the Ferocious 29932
should be heroic mode only

graphical terrain error in middle room when you cross the bridge. your character moves "inside" the bridge.

**Comment by Damieninabox** [comment]
Fixed Slad'ran drop, could not reproduce Eck (only spawned in heroic on my end)
