### ISSUE TITLE
[WARRIOR] Glyph of Weaponmaster

### ISSUE THREAD

**Issue by sambrox** [Damieninabox/Lotus-WoW-Bugtracker#195]
**Describe the bug**
Glyph of Weaponmaster doesn't change weapon's appearance with any weapon in primary bag.

**To Reproduce**
Apply Glyph of Weaponmaster, have at least one weapon in your primary bag and use Battle Shout/Commanding Shout.

**Screenshots**
![image](https://user-images.githubusercontent.com/75437251/145075320-dfcfd656-4e02-4053-82f9-f5629fbc0c3b.png)

**Comment by Damieninabox** [comment]
Fixed with next core update
