### ISSUE TITLE
[Spell] Control Pet

### ISSUE THREAD

**Issue by irrefutable** [Damieninabox/Lotus-WoW-Bugtracker#20]
https://www.wowhead.com/spell=93321/control-pet - doesn't work. You're able to control it even before Level 10 (See the bar with pet commands in the screenshot)
![CapturePetBar](https://user-images.githubusercontent.com/46446681/144674414-deec0b71-1078-4016-b852-5f910e86c0c5.PNG)
.

**Comment by Damieninabox** [comment]
Fixed with next server update
