### ISSUE TITLE
[Quests] Mount Hyjal

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#200]
Respawn times are very long for mostly all mobs. imo its too long.

Phasing in Shrine of Goldrinn is kinda messed up. 
Quest NPC still in cage after you conquered the camp. 
Mobs still in camp after you conquered camp.
Two of the same wolf-npc in camp.

Quests:
Free Your Mind, the Rest Follows 25298
group progress missing, to few npcs, respawn to high

Gar'gol's Gotta Go 25328
Gar'gol's Personal Treasure Chest 204580 respawn timer way to high

Get Me Outta Here! 25332
No trigger for Groupmember to accept quest if one player starts it. Quest will not get autoshared
Kristoff Manheim 39640 not moving correctly with player starting the quest - cant complete quest

A New Master 25411
Subjugated Inferno Lord Quest Credit 40099 spawns and instant falls through the ground/earth.
quick workaround: kill infernoloard on rock tarrain and summon questnpc on the rock. will not fall then.

NPC: Tyrus Blackhorn 39933
offers you quest before you complete prequest, 
iirc the quest was: "Seeds of Their Demise" 25408 before completing "If You're Not Against Us..." 25404
should not do that until you complete prequest to maintain questchain

to be continued ...

**Comment by Damieninabox** [comment]
Entire cataclysm zones will get merged over from our old cataclysm source (will be done in the future) -> quest by quest, phasing for each zone etc.
