### ISSUE TITLE
[Quest] Return to Sentinel Hill (https://www.wowhead.com/quest=26370/return-to-sentinel-hill)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#201]
**Describe the bug**
Phasing bug. Npcs are no longer within the area.

**To Reproduce**
Steps to reproduce the behavior: Accept the quest and fly to Sentinel Hill.
Location: West Fall - Sentinel Hill.
Name, Type
Problem Description: Cannot complete the quest Return to Sentinel Hill due to phasing bug. Npcs do not appear in the area.
How it should work: Gran Shoutmantle should be next to the flight path npc upon landing.
Video: https://www.youtube.com/watch?v=JUqmAu1BIWQ

**Screenshots**

Outside of Sentinel Hill, you can still see the npcs.
![westfall with npcs](https://user-images.githubusercontent.com/95708111/145106486-f58e144b-e9a6-497c-8162-81ac42983353.jpg)

Inside, they are no longer there.
![westfallphase without npcs](https://user-images.githubusercontent.com/95708111/145106497-49e8143f-4f79-442a-8a25-a03b77cd5abe.jpg)

**Additional context**
You can see the quest icon when you're near the area, but it disappears as soon as you approach the tower.

**Comment by Damieninabox** [comment]
Fixed with next restart
