### ISSUE TITLE
[Quest] In Search of Bravo Company. (https://www.wowhead.com/quest=26586/in-search-of-bravo-company)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#204]
**Describe the bug**
Simply, NPC Messner (https://www.wowhead.com/npc=43270/messner) is missing from his cage. I also believe this causes later bugs within the quest chain.

**To Reproduce**
Steps to reproduce the behavior: Accept the quest from Colonel Troteman. (https://www.wowhead.com/npc=43221/colonel-troteman) and make your way to Alther's Mill. 
Location: Redridge Mountains. Alther's Mill.
Messner, NPC
Problem Description: Messner does appear inside the cage at all. Cannot complete the quest.
How it should work: Messner should be within the cage to complete the quest.

**Screenshots**
Messner not within the cage.
![Messner missing](https://user-images.githubusercontent.com/95708111/145264784-3eb2eafe-3124-429f-b6e8-66835ababa96.jpg)

**Additional context**
As mentioned before, this may be a quest chain issue further on into the chain.

**Comment by Damieninabox** [comment]
Fixed with next update
