### ISSUE TITLE
[Quest] Saving Foreman Oslow. (https://www.wowhead.com/quest=26520/saving-foreman-oslow)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#206]
**Describe the bug**
The rock that is necessary to be by the bridge, is not there. Neither is Foreman Oslow. (https://www.wowhead.com/npc=341/foreman-oslow) 

**To Reproduce**
Accept quest from the Ettin Control Orb (https://www.wowhead.com/object=204351/ettin-control-orb) inside of Rethban Caverns. Make your out of the cave and find the wandering Ettin giant. Use the Ettin Control Orb on the Ettin Troll and head towards the bridge in lakeshire. There will not be a stone, nor will there be npcs surrounding that stone as shown in the quest video.
Location: Lakeshire.
Problem Description: There is no stone, nor any npcs near the Lakeshire bridge.
How it should work: Foreman Oslow should be trapped under the stone, and the Troll should be lifting the stone. 

**Screenshots**
A clear path with no stone, nor any npcs surrounding it.
![No stone nor NPCs](https://user-images.githubusercontent.com/95708111/145281069-55c0ae1b-8af4-495a-9e67-efa3df48d8e5.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next server restart
