### ISSUE TITLE
[Death Knight] Glyph of Foul Menagerie

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#207]
**Describe the bug**
The Glyph enables you to call forth an assortment of undead minions to fight by your side however its still only calling the default ghouls

**To Reproduce**
Equip Glyph of Foul Menagerie, Activate Army of the Dead spell 
**Screenshots**
![Menagerie](https://user-images.githubusercontent.com/95563818/145285288-3046da7f-dcf1-4a61-ae63-9eb0f907dbae.PNG)

**Comment by Damieninabox** [comment]
Already fixed with next core update -> duplicate
