### ISSUE TITLE
Thunder Hold npc damage output

### ISSUE THREAD

**Issue by Zirda** [Damieninabox/Lotus-WoW-Bugtracker#21]
https://mop-shoot.tauri.hu/?npc=66285

These NPCs are hitting for way harder than they should. All of these Thunder hold NPCs are hitting in the 10-15k range normal hits. 

![bild](https://user-images.githubusercontent.com/3477311/144674793-97b69c10-4f71-4abf-b03e-6e1317a571b2.png)

**Comment by Damieninabox** [comment]
Fixed
