### ISSUE TITLE
1st Dialogue Taran Zhu - General Nazgrim

### ISSUE THREAD

**Issue by grtandyllw** [Damieninabox/Lotus-WoW-Bugtracker#212]
Just a minor typo. after finishing the quest https://www.wowhead.com/quest=31769/the-final-blow, taran zhu should say "You should [...]" 

To reproduce, finish quest stated above.

![WoWScrnShot_120821_232325](https://user-images.githubusercontent.com/95633065/145294239-2a01334d-2134-4099-90cb-47d30f59a982.jpg)

**Comment by Damieninabox** [comment]
Fixed with next restart
