### ISSUE TITLE
[Quest] Mind Control (https://www.wowhead.com/quest=26774/mind-control)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#214]
**Describe the bug**
Braddok (https://www.wowhead.com/npc=42858/braddok) doesn't drop his brain each kill. It took me 3 kills to get his brain.

**To Reproduce**
Steps to reproduce the behavior: Accept Mind Control quest and go kill Braddok.
Location: Stranglethorn Vale - Ruins of Zul'Mamwe
Braddok, NPC
Problem Description: Braddok's big brain (https://www.wowhead.com/item=58225/braddoks-big-brain) has a low drop rate. (quest items like this should be 100%)
How it should work: Braddok should drop his brain after 1 kill.

**Screenshots**
![No brain](https://user-images.githubusercontent.com/95708111/145315100-2c44bf9a-6ff9-4d28-979d-a1073121461b.jpg)

**Additional context**
This may be wrong, but as I mentioned, its a quest item, for a single npc. Let's not create lines of people waiting for a simple quest.

**Comment by Damieninabox** [comment]
Fixed with next restart
