### ISSUE TITLE
[Glyph - Death Knight] Glyph of Resilient Grip

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#216]
**Describe the bug**
This Glyph (https://wowpedia.fandom.com/wiki/Glyph_of_Resilient_Grip) is not working as intended

**To Reproduce** (I describe my discovery method but this can be replicated on any 'Immune' enemy)
Head into the Cataclysm Dungeon 'The Stonecore (HC)'
Before the 2nd boss there are big ogre mobs called 'StoneCore Bruisers'
They are displacement-immune and when using spell 'Death Grip' cannot be pulled and a notification 'Immune' pops up

**Bug** However the cooldown of Spell Death Grip is NOT reset

**Comment by Damieninabox** [comment]
Fixed with next core update
