### ISSUE TITLE
Item - Malik's Stalwart Spear

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#218]
**Describe the bug**
Item disappears before you can loot it

**To Reproduce**
Steps to reproduce the behavior: Right click item 

Location Dread Wastes - Location in SS will be in tree infront

How it should work
Item should be lootable 
https://www.wowhead.com/object=213964/maliks-stalwart-spear

![WoWScrnShot_120921_132515](https://user-images.githubusercontent.com/95519949/145462461-22af6dc4-c602-4258-bc7a-e2ce34452f36.jpg)
![WoWScrnShot_120921_132513](https://user-images.githubusercontent.com/95519949/145462469-00aa731d-96d5-401f-86bd-27a95e165f6c.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next restart
