### ISSUE TITLE
NPC - Oracle Hiss'ir

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#221]
**Describe the bug**
Casts Recall of the World (Old)
Has infinite (maybe) leash range
Not in combat past a certain range
Does not cast his listed wowhead spells

**To Reproduce**
Steps to reproduce the behavior: attack and run away!
Location - Dreadwastes - The Briny Muck

**How it should work** 
His leash range should be much short, maybe just his island a bit past
https://www.wowhead.com/npc=63998/oracle-hissir#abilities
**Screenshots**
![WoWScrnShot_120921_143226](https://user-images.githubusercontent.com/95519949/145471610-9401994e-9ce2-4f46-8cc9-bcc7ffb27237.jpg)

**Comment by Damieninabox** [comment]
Fixed with next core update
