### ISSUE TITLE
Quest - The Dissector Wakens

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#222]
**Describe the bug**
Spawns only 2 mobs and gives insane amount of gold
Gave 283g 20 silver, shouldn`t be anywhere near this. 

**To Reproduce**
Steps to reproduce the behavior: accept quest after completing Zanthik Dig  

Location Dread Wastes - Amber Quarry 

How it should work
4 mobs should spawn 1 at a time
Gold should be about 39g 69 silver (This is what Dread Clutches and Not fit to Swarm give and they are kill quests)

Gold amount in bottom left corner from Quest
![WoWScrnShot_120921_151842](https://user-images.githubusercontent.com/95519949/145477211-0cd70757-3c97-442d-90c7-0f00df6e1eb9.jpg)

**Comment by Damieninabox** [comment]
Fixed the money part

**Comment by Damieninabox** [comment]
Fixed with next core restart
