### ISSUE TITLE
NPC - Paragons Appearing without doing prerequisites 

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#224]
**Describe the bug**
Several of them appear outside but have copies inside Klaxxi'vess as well.

Xaril the Poisoned Mind is now appearing as well

Korven the Prime is appearing in Klaxxi'vess without doing his quest chain to unlock him
Appears to be doing this at honored rep (which is when his daily quests unlock)
He also seems to repeat his RP in rapid succession

**To Reproduce**
Steps to reproduce the behavior: Seems to be when you have honored reputation with the Klaxxi
Location Dread Wastes - Klaxxi'vess

How it should work
Shouldn't appear until his quest chain is finished at Lake of Stars

**Screenshots**
![WoWScrnShot_120921_163153](https://user-images.githubusercontent.com/95519949/145486652-545615fb-02c1-4b35-86de-270cc975cbd2.jpg)
![WoWScrnShot_120921_164508](https://user-images.githubusercontent.com/95519949/145487639-1cefdf93-d197-4494-8881-722b8f768f38.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next core/database update
