### ISSUE TITLE
Raid - Heart of Fear | Several issues on bosses

### ISSUE THREAD

**Issue by Anakia69** [Damieninabox/Lotus-WoW-Bugtracker#225]
_**Describe the bug**_

IMPERIAL VIZIER ZOR'LOK

- Techniques are added to each platform (there should be one technique per platform) = bug to be confirmed, happened before the 15 min restart ;
- Mind control : you can't hit players under the effect of the spell. Also, our Warlock has been MC'ed and none of his spells have been used, he kept hitting with his sword, nothing else ;
- Almost no damage when under "Force and Verve", damage inflected to players seems to be too low while shielded by "Noise Cancelling" zones ;
- Exhale : the tank can't cut the link to cancel the spell.

GARALON :

- "_Garalon periodically mends **ONE** of his legs [every 30s]_" => on Lotus, several legs can respawn at the same time and within that 30 second counter. That is a HUGE problem.

MEL'JARAK :

- Not enough Wind Bombs seem to spawn during P2 ;
- Corrosive Resin does not seem to spawn on each move of the targeted player.

UN'SOK :

- Mutated Construct : they are impossible to hit as they are considered allies ;
- Amber Explosion : self kick [to cancel the incanted spell] not always possible.

SHEK'ZEER :

- Spawn of the "Dissonance Field" at the time of the transition in P2 (it shouldn't). See this : _"Twice during Phase One (30 seconds into the phase, and 60 seconds after that) Shek'zeer will place two Dissonance Fields on the ground, a little way apart from one another._ 
=> timers look wrong on Lotus, if you watch my stream, Exorcus (addon) tracks the length of the fight and you can see that they spawn on wrong timers ;
- Windblades run at normal speed when they "Fixate" people. Should be: "_Fixate sometimes causes the Windblade to fixate on a random target, moving towards that target at highly reduced movement speed._" ;
- Every Windblade used their "Fixate" spell on the entire raid when in logic, there are only 1 or 2 maximum at the same time.

_**To Reproduce**_

Try HoF ! :)

_**Screenshots**_

See our streams below :
https://www.twitch.tv/videos/1228818262
https://www.twitch.tv/videos/1228784876

_**Additional context**_

Guild name : Eternal Symphonia, Char name : Bringbackdxe, Discord : Malax#7387

**Comment by SimonM-49** [comment]
To complete the report

UN'SOK :
Mutated Construct : they are impossible to hit as they are considered allies ;
_=> To add to this issue, they can be hit by some AOE spells, like rain of fire (warlock), or consecration (paladin), but it's impossible to target them and use singles attacks on them_


IMPERIAL VIZIER ZOR'LOK:
Mind control : you can't hit players under the effect of the spell. Also, our Warlock has been MC'ed and none of his spells have been used, he kept hitting with his sword, nothing else ;
_=> Same as Un'sok, AOE spells seems to hit controlled players, and after quite some times, we ould focus minded players (about maybe 15-20 sec), and CM doesn't seems to do much, I did around 3-4 sword hit as a warlock under 3 CM, not spells/CD casts_

SHEK'ZEER :
Spawn of the "Dissonance Field" at the time of the transition in P2 (it shouldn't). See this : "Twice during Phase One (30 seconds into the phase, and 60 seconds after that) Shek'zeer will place two Dissonance Fields on the ground, a little way apart from one another.
=> timers look wrong on Lotus, if you watch my stream, Exorcus (addon) tracks the length of the fight and you can see that they spawn on wrong timers ;
_=> You also can't go inside one the dissonance field without the Cry of Terror debuff to make it explode faster by casting spell inside, you are bump outside if you try to go inside without the debuff. With the debuff you can go inside without issue, but as soon as your debuff is over, you are bump outside._

**Comment by Greymane** [comment]
Mel'Jarak issues deemed **INVALID**.

* Pools of resine do spawn properly if you move, as you can see [here](https://i.gyazo.com/27020c93a3dc0643a7ec5f5d82207a76.gif).
* Wind Bombs have a MaxAffectedTarget attribute set to 1 in DBC, and in Fatboss's [25 man](https://www.youtube.com/watch?v=X_FWqPvNoCk&t=431s) and [10 man](https://www.youtube.com/watch?v=HdD0VmY9pHk&t=449s) versions of the boss, it shows only 1 bomb spawning at a time.

**Comment by Anakia69** [comment]
Hopefully fixes have been made here!

**Comment by Greymane** [comment]
Un'Sok issues also deemed **INVALID**

* Player Mutated Constructs [can be directly attacked](https://gyazo.com/7a7f8779e8566bdc78e4ef91b5cda831), not just with AoE.

* Self Kick [also appears](https://gyazo.com/7c2bb930d02cbb5ff261756a7ff3f513) to be working properly.

Both mechanics were tested outside and during the encounter.

**Comment by Greymane** [comment]
@Anakia69 @Theralion What should happen to non-expired dissonances when the empress transitions in phase 2? should they just explode and wipe all the raid for not being able to consume them fast enough? (timers for it are now corrected)

**Comment by Anakia69** [comment]
Well they should just keep going and explode when they run out of energy. It is the raid job to avoid that by soaking them (so they explode faster) since it definitely increases wipe chances.

**Comment by Greymane** [comment]
Alright, thanks
