### ISSUE TITLE
NPC - Mistblade Ripper

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#227]
**Describe the bug**
Mistblade Ripper are casting unstable serum when they use Shadowstep

**To Reproduce**
Steps to reproduce the behavior: Attack Mistblade ripper wait until it uses Shadowstep
Location Dread Wastes - Lake of Stars

How it should work
Should not cast Unstable Serum
https://www.wowhead.com/spell=127373/unstable-serum
https://www.wowhead.com/npc=61970/mistblade-ripper#abilities

**Screenshots**

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next core update
