### ISSUE TITLE
Buff - Mazus Breath not working

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#228]
**Describe the bug**
Does not give speed increase nor does it give water breathing

**To Reproduce**
Steps to reproduce the behavior: Complete Mazu`s Breath quest and be in Shelf of Mazu and Lonesome Cove

Problem Description
How it should work
Swim speed should be increased by 80% while in water in Shelf of Mazu and Lonesome Cove
Should have water breathing
**Screenshots**
![WoWScrnShot_120921_184624](https://user-images.githubusercontent.com/95519949/145498283-9994b53a-cb28-4eae-a1cc-2235464e232b.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next server restart
