### ISSUE TITLE
[Quest] Eliminate the threat (https://www.wowhead.com/quest=26810/eliminate-the-outcast)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#229]
**Describe the bug**
The quest autocompletes as soon as you are near Zanzil's Portal in Ruins of Aboraz. There is no MAP ICON informing you of the quest completion. (where to turn in the quest, although it's obvious where). Upon handing in the quest, you do not recieve the follow up quest **Through the Troll Hole** (https://www.wowhead.com/quest=26811/through-the-troll-hole) , causing you to be unable to finish the quest chain. 

**To Reproduce**
Begin Eliminate the Threat by talking to Maywiki (https://www.wowhead.com/npc=44084/maywiki) at Explorer's League Digsite. Head over to Ruins of Aboraz and auto complete the quest at Zanzil's Portal. Return to Miywiki and hand in the quest. She will not have a follow up quest.
Location: Stranglethorn Vale - Explorer's League Digsite.
Problem Description: When the quest auto completes, there is no follow up in the objectives tab.
How it should work: There should be a follow quest as soon as you complete the quest.

**Screenshots**
Auto completed but no immediate follow up on the objectives tab.
![auto complete eliminate the threat](https://user-images.githubusercontent.com/95708111/145586735-553a9bb1-cebf-4300-ac8f-b46a265b66f1.jpg)
Quest is finished and you can hand it in to Maywiki.
![quest is actually finished](https://user-images.githubusercontent.com/95708111/145586175-f9d71795-b3f4-4245-b7b9-03aefe32813f.jpg)
Quest icon is missing, but this might be intentional due to the immediate follow up quest that's supposed to occur.
![quest icon missing on map](https://user-images.githubusercontent.com/95708111/145586414-15479aa0-a203-49f2-a824-ca089a8a90b9.jpg)

**Additional context**
You retain Maywiki's Fetish (https://www.wowhead.com/item=60374/maywikis-fetish) after manually completing this quest. It CAN be completed, but there is no further follow up in the chain from Maywiki herself.

**Comment by Damieninabox** [comment]
Fixed the entire quest chain
