### ISSUE TITLE
Trial Master Rotun not allowing to queue for Proving Grounds

### ISSUE THREAD

**Issue by Joekekw** [Damieninabox/Lotus-WoW-Bugtracker#23]
**Describe the bug**
Hi All,

NPC Username: Trial Master Rotun
Location: Temple of the White Tiger - Kun'Lai Summit
NPC ID: 72536

Is not allowing to queue for proving grounds, screenshot attached.

**To Reproduce**

1. Go to Temple of the White Tiger, Kun'Lai Steps.
2. Enter the main building and try to queue.

**Screenshots**
![WoWScrnShot_120321_220528](https://user-images.githubusercontent.com/51991242/144679070-a7e0dcdc-98db-443a-8856-f5874424b1b2.jpg)

**Additional context**
I'm not 100% sure if you're meant to queue from here in this patch.
Zephyr asked me to log it anywau

**Comment by Damieninabox** [comment]
Can't reproduce
