### ISSUE TITLE
[Quest] Shocking!

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#231]
**Describe the bug**
This quest (https://www.wowhead.com/quest=30584/shocking) involves fishing up Dojani Eels (https://www.wowhead.com/item=80260/dojani-eel) 
The quest is much easier and faster to complete at lower levels of fishing vs when you have high fishing skill. 

**How it should work** : Quest becomes easier/trivial once your fishing skill is high

**To Reproduce**
Take the quest when at Fishing Skill zero. (You will be able to get eels while your fishing level increases and complete quest in one sitting)
Take the quest when at 200+ or 300+ fishing skill. (The drop rate is significantly minimized mostly in favor of getting other high-level fish)

**Additional context**
Angler's faction daily quest

**Comment by Damieninabox** [comment]
Adjusted with next update
