### ISSUE TITLE
evangelism stacks increase Penance healing componement

### ISSUE THREAD

**Issue by ashruner** [Damieninabox/Lotus-WoW-Bugtracker#232]
**Describe the bug**
Evangelism stacks are supposed to increase damage of smite , holy fire and penance of 4% per stacks , stacking 5 times thats 20 % damage increase but it also increase penance healing when used on a ally by the same amount (first tick 38 k healing with stacks , 31k without them)

**To Reproduce**
get on a disc priest , remove trinkets , cast penance on self , see the amount of first tick , stack evangelism , cast penance on self again and compare 

**How it should work**
Evangelism stacks should only increase penance power when used against an ennemy 

**Additional context**
N/A

**Comment by Greymane** [comment]
![image](https://user-images.githubusercontent.com/671155/151194802-5550729f-10e8-44c7-9ee2-6196e5bb4ead.png)

@ashruner
"Increases the damage AND HEALING done by your PENANCE....etc etc"
I think thats quite clear that's how the spell is supposed to work, moreover, evangelism does have proper spellclassmask (the attribute that lists the affected spells) on the SpellMod effect for the damage/healing parts of penance. I'll be marking this one as invalid and closed until further proof is provided.
