### ISSUE TITLE
Quest - Reeltime Strategy 

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#233]
**Describe the bug**
There should not be 4 Jiao Spawn after completing the mini event and phasing into the next phase

**To Reproduce**
Steps to reproduce the behavior: complete quest until Angler Ju Lien is taken by Jiao Tentacle
Location Dread Wastes - Soggy's Gamble
Problem Description
Jiao Spawn should not spawn/phase around the Angler Ju Lien's fishing spot

**Additional context**
https://youtu.be/xPmkjrs8274?t=99

**Comment by Damieninabox** [comment]
Fixed
