### ISSUE TITLE
NPC - Jiao Spawn

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#234]
**Describe the bug**
Hit too hard (around 10k critting more than 20k) on a 496 ret paladin
Are aggressive 

**To Reproduce**
Steps to reproduce the behavior: Be in the Jiao phase in Soggy's Gamble
Location Dread Waste - Soggy's Gamble

Problem Description
Jiao spawn should hit around 2.4-2.7k on a blue geared paladin 
Should be neutral mobs and only aggressive during Reeltime strategy when you reel them in

Start of combat https://youtu.be/xPmkjrs8274?t=42
Showing Neutral https://youtu.be/xPmkjrs8274?t=119

**Screenshots**

Combat log of Jiao spawn hitting me so hard
![WoWScrnShot_121121_011833](https://user-images.githubusercontent.com/95519949/145668336-ed0c2c76-48fb-4f19-9719-8866c17489f7.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Adjusted with next server restart
