### ISSUE TITLE
NPC - Dread Remora 

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#236]
**Describe the bug**
Hits too hard.

**To Reproduce**
Steps to reproduce the behavior: attack one
Location Dread Wastes Muckscale Shallows 

Problem Description
Should melee hit roughly around 6.5-7k with weakened blows (10% physical dmg reduction) and on a blue geared paladin and glyph of TV (10% dmg reduction)
Ability Symbiotic Subsistence should hit for 7.2k not 8k 
**Screenshots**
combat log - against a 496 paladin
![WoWScrnShot_121121_015218](https://user-images.githubusercontent.com/95519949/145669108-31cfc1a1-4de9-4481-ae18-0b801faf40a9.jpg)
8k hit were with Weakened blows debuff and with TV glyph 
![WoWScrnShot_121121_020109](https://user-images.githubusercontent.com/95519949/145669278-00d7a061-5b19-4b07-a8ea-3a1d7c0ac6d4.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Adjusted with next server restart
