### ISSUE TITLE
Object - Blade of the Prime

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#238]
**Describe the bug**
Completed quests for Korven the Prime at Lake of Stars. It appears phasing has phased it out
Blade of The Prime also had the same problem as Malik's Spear and disappeared before looting (had tested this earlier)

**To Reproduce**
Location Dread Wastes - Lake of Stars cave
Name, Type
Problem Description
Should appear in all phasing 
Should disappear after looting 

https://www.wowhead.com/item=86522/blade-of-the-prime

**Screenshots**
![WoWScrnShot_121121_024418](https://user-images.githubusercontent.com/95519949/145670428-20312b5e-5be3-472d-99d5-6eebf675f74b.jpg)

**Comment by Damieninabox** [comment]
Fixed with next restart
