### ISSUE TITLE
[Quest] Turning the Brashtide (https://www.wowhead.com/quest=26699/turning-the-brashtide)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#241]
**Describe the bug**
Brashtide Raiders (https://www.wowhead.com/npc=43716/brashtide-raider) do not spawn at booty bay.

**To Reproduce**
Enter Booty Bay and accept Turning the Brashtide.
Location: Booty Bay.
Name, Type
Problem Description: Brashtide Raiders do not spawn at booty bay.
How it should work: Brashtide Raiders should spawn in Booty Bay.

**Screenshots**
![Brashtide raiders 1](https://user-images.githubusercontent.com/95708111/145688065-2829f2c6-cb04-48c2-a523-3322ba47c16d.jpg)
![Brashtide raiders 2](https://user-images.githubusercontent.com/95708111/145688067-a0d98c22-4cb8-47a7-897e-8a5bc84d138b.jpg)

**Additional context**
This might be a phasing issue, because Blood Sail Corsair (https://www.wowhead.com/npc=43726/bloodsail-corsair) also doesn't spawn for another quest.

**Comment by Damieninabox** [comment]
Fixed some time ago
