### ISSUE TITLE
[Quest] The Damsel's (Bad) Luck. (https://www.wowhead.com/quest=26700/the-damsels-bad-luck)

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#242]
**Describe the bug**
Bloodsail Corsair (https://www.wowhead.com/npc=43726/bloodsail-corsair) does not spawn in booty bay. Their ship is also not in the vacinity. The current Booty Bay is not phased for this quest accordingly. Fleet Master Seahorn (https://www.wowhead.com/npc=2487/fleet-master-seahorn) is not in the proper location as well.

**To Reproduce**
Enter Booty Bay and accept the quest. Nothing will happen, and no Bloodsail Corsairs will be found.
Location: Booty Bay.
Name, Type
Problem Description: Bloodsail Corsair does not spawn in Booty Bay, nor does the ship.
How it should work: Bloodsail Corsair should spawn in booty bay, along with their ship.

**Screenshots**
The Ship the Bloodsail Corsairs are supposed to be on, is missing. Fleet Master Seahorn is also not in his proper location.
![Fleet Master not in his location ship is missing](https://user-images.githubusercontent.com/95708111/145688529-73ed9846-22a8-4cc1-b450-e8cb7561781b.jpg)
Fleet Master Seahorn is in his old location.
![Fleet master wrong location](https://user-images.githubusercontent.com/95708111/145688560-25e34ca5-7313-469a-91f9-2c57859c6ea0.jpg)

**Additional context**
This must definitely be a phasing issue, because booty bay is also not on fire or under attack. (video: https://www.youtube.com/watch?v=Yq6KKvfzRXs)

**Comment by Damieninabox** [comment]
Fixed with next update, also adjusted overall quest chains, combat AI and follow up quests
