### ISSUE TITLE
**WILL FINISH LATER**[Quest] The Final Voyage of the Brashtide (https://www.wowhead.com/quest=26697/the-final-voyage-of-the-brashtide) 

### ISSUE THREAD

**Issue by LydiaFavre** [Damieninabox/Lotus-WoW-Bugtracker#243]
**Describe the bug**
This entire quest is completely 

**To Reproduce**
Location
Name, Type
Problem Description
How it should work

**Screenshots**
You can still use the windrider from the npc.
![Kebob allows you to use the windrider](https://user-images.githubusercontent.com/95708111/145689449-7c6f8235-3390-4c8b-af57-e84b498c201e.jpg)
But he sends you to the wild shores on one of the ships.
![Kebob sends to a ship around the wild shores](https://user-images.githubusercontent.com/95708111/145689461-fe45e95a-c06c-410a-8013-55cbffb54e06.jpg)
No ship nor npcs to kill in the quest zone.
![Spawn area has no ship or npcs](https://user-images.githubusercontent.com/95708111/145689421-876c0edc-620a-419d-872b-416170279945.jpg)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed some time ago
