### ISSUE TITLE
[Spell] Unleash Elements

### ISSUE THREAD

**Issue by irrefutable** [Damieninabox/Lotus-WoW-Bugtracker#244]
**Describe the bug**
When using SpellID = 73680 (Unleash Elements) with resto shaman enchantment Earthliving Weapon SpellID = 51730 and targetting an enemy it doesn't do anything - no buff applied to self.

**To Reproduce**
Duel someone or be in combat with something targetting anything but self and try and use it. It won't work.

**Comment by Damieninabox** [comment]
Fixed with next core update
