### ISSUE TITLE
Kun-Lai Summit visible Observer

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#245]
**Describe the bug**
Observer entity is visible to players while it should not be 
![WoWScrnShot_121321_165445](https://user-images.githubusercontent.com/80163881/145844755-e17be745-e61e-4b61-adde-f661bc8de386.jpg)

**To Reproduce**
Go to Kun-Lai at 55.53 42.99

**Comment by Damieninabox** [comment]
Fixed with next restart
