### ISSUE TITLE
Misplaced NPC Kyo Che Wildwalker's Pet in Kun-Lai Mountains

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#246]
**Describe the bug**
https://www.wowhead.com/npc=63769/kyo
There are two of these NPC's in Kun-Lai Summit seemingly for no reason

I don't know if there is supposed to be more here, which would explain their existence. But its also wierd that there are two.

**To Reproduce**
Locate the two NPC's at coordinates (56.59, 43.43) and (56.00, 43.41)

**Screenshots**
![WoWScrnShot_121321_170110](https://user-images.githubusercontent.com/80163881/145845978-68a38325-f6e4-48e0-a1e7-365f12a2bd5c.jpg)
![WoWScrnShot_121321_170121](https://user-images.githubusercontent.com/80163881/145845982-bba65ac8-b126-465e-942a-b84820e75a33.jpg)

**Comment by Damieninabox** [comment]
Fixed with next restart
