### ISSUE TITLE
Lor'themar Theron aggressive to horde in Kun-Lai Summit

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#247]
**Describe the bug**
https://www.wowhead.com/npc=68370/lorthemar-theron
https://www.wowhead.com/npc=68431/blood-knight
https://www.wowhead.com/npc=68384/aenea

Are hostile towards horde, they should not be.

**To Reproduce**
Go to location (53.78, 49.09) as horde and get attacked

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/145847832-8be8c47b-6fa3-4e01-872e-85e6f4fc92df.png)

**Comment by Damieninabox** [comment]
Fixed with next restart
