### ISSUE TITLE
Crates dropping randomly

### ISSUE THREAD

**Issue by Alurienia** [Damieninabox/Lotus-WoW-Bugtracker#25]
**Describe the bug**
In Durotar, Near Sen'jin Village The alliance NPC's carrying crates randomly drop their crates

**To Reproduce**
Unknown. 

**Screenshots**
![image](https://user-images.githubusercontent.com/37201167/144679621-6a05bdee-f756-46b0-bf1b-0f0f4a0f863f.png)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next server update
