### ISSUE TITLE
[NPC] Shado-Pan Marksman sitting with no weapon

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#254]
**Describe the bug**
Shado-Pan Marksman have bows and stand up, they currently sit and do nothing. 
https://www.wowhead.com/npc=64260/shado-pan-marksman

**To Reproduce**
Find Shado-Pan Marksman on the great wall (15.94, 17.22)

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/146074797-12a596f6-1f7b-40fe-942d-1c2cca375a3e.png)

**Comment by Damieninabox** [comment]
Fixed with next server restart
