### ISSUE TITLE
[NPC] Gai Cho enemies too dense

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#255]
**Describe the bug**
I would argue that the density of these enemies is too high at the foot of the mountain
https://www.wowhead.com/npc=62589/gai-cho-boltshooter
https://www.wowhead.com/npc=62577/gai-cho-cauterizer
https://www.wowhead.com/npc=62568/gai-cho-gatewatcher

**To Reproduce**
Go to: (60.30, 48.50)

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/146077612-c3042adf-f9e0-430f-864e-2fbb8a98222b.png)

**Comment by Damieninabox** [comment]
Adjusted on the live server
