### ISSUE TITLE
[NPC] Summit prowlers invalid pose

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#256]
**Describe the bug**
https://www.wowhead.com/npc=59534/summit-prowler#screenshots
Alright hear me out, all the prowlers I found were sleeping. But the wowheads screenshots show them sitting or standing.
Even more importantly, they are said to sometimes dance according to a comment.

**To Reproduce**
Go to (41.36, 64.38)

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/146079135-30f6d131-f590-424f-8685-3028baf05acc.png)

**Comment by Damieninabox** [comment]
Fixed with next restart
