### ISSUE TITLE
Quest - Onyx to Goodness

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#258]
**Describe the bug**
Text is incorrect for player's name in hand in quest text
**To Reproduce**
Steps to reproduce the behavior: Start to hand in Quest
Location Jade Forest - Arboretum

How it should work
Should say my name! 

**Screenshots**
![WoWScrnShot_121521_010534](https://user-images.githubusercontent.com/95519949/146139602-093a0538-0489-4221-aa8c-a5c800bdfd06.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server restart, make sure to delete your Cache
