### ISSUE TITLE
Map bug after fear > find myself under Orgrimmar

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#261]
Hey Zeph and Damien

Just wanted to report a bug I encountered while duelling in front of Orgrimmar. I got feared by a Paladin and flead into a wall. Down down under the map I went (without any parachute).
I got killed tried to ankh but died again immediatly.

To reproduce I guess getting feared towards the wall I screenshot might get you under map.
It's the one on the right facing the transmog vendor you put, behind the NPCS for professions and pve goods.

It's not a massive bug but hey, might as well let you know.

Cheers lads and keep up the good work.

Hail lotus
![WoWScrnShot_121521_221516](https://user-images.githubusercontent.com/96208507/146268012-3e831cce-b6b7-48ca-895a-53509de07f34.jpg)
![WoWScrnShot_121521_221556](https://user-images.githubusercontent.com/96208507/146268727-cae41225-bf58-4d60-825d-b97d824a1bc6.jpg)
![WoWScrnShot_121521_221609](https://user-images.githubusercontent.com/96208507/146268751-5b243b3b-afbc-4546-97aa-d56febf76727.jpg)
![Uploading WoWScrnShot_121521_221556.jpg…]()
![Uploading WoWScrnShot_121521_221609.jpg…]()

**Comment by Damieninabox** [comment]
Have you tried this in other situations/locations?
