### ISSUE TITLE
Lay on Hands

### ISSUE THREAD

**Issue by Ohpala** [Damieninabox/Lotus-WoW-Bugtracker#263]
633: Lay on Hands

**Describe the bug**
it's not healing the correct value

**To Reproduce**
https://youtu.be/9-q-qmKNdZw

in the skill's description, it says that it heals a value equivalent to the  equal to your maximum health.

Lay on Hands
40 yd range
Instant
10 min cooldownn
Heals a friendly target for an amount equal to your maximum health.Cannot be used on a target with Forbearance. Causes Forbearance for 1 min.

**Additional context**

in case there's something wrong, unfortunately I had to use google translate because I don't speak english

**Comment by Damieninabox** [comment]
Additional info:

Lay on hands seems to heal more than the casters maximum health (also gotta check if lay on hands is currently reduced by battle fatigue?)

**Comment by Ohpala** [comment]
in the video shown is not affected by fatigue, but is affected when used in pvp

**Comment by Damieninabox** [comment]
Yeah sorry, was meant to be additional information for developers

**Comment by Ohpala** [comment]
ah q-q
