### ISSUE TITLE
Unstable Affliction

### ISSUE THREAD

**Issue by Ohpala** [Damieninabox/Lotus-WoW-Bugtracker#264]
Spell: 30108
Silence caused by dispelling spell: 31117

**Describe the bug**
The silence caused after dispelling the Unstable Affliction is being affected by Dr (Diminishing returns).

**To Reproduce**
https://youtu.be/u1uhxZxaV1w

**Additional context**
https://wowpedia.fandom.com/wiki/Diminishing_returns
On this site contains all abilities that are affected by DR

**Comment by Damieninabox** [comment]
Fixed with next core update
