### ISSUE TITLE
Lightning Shield

### ISSUE THREAD

**Issue by Ohpala** [Damieninabox/Lotus-WoW-Bugtracker#266]
**Describe the bug**
Shaman's lightning shield has a cooldown of 1.5s

**To Reproduce**
The damage done by the Shaman's Lightning Shield is 1.5s, his correct cooldown should be 3s (according to Bonus (2) of the Elemental PvP Set).
> https://postimg.cc/v195SFs3

**Screenshots**
> https://youtu.be/mePq5yoD-pY
In the video was tested without specialization
**Additional context**
To be more direct, its correct cooldown  is >3s(correct)<, but it has a >1.5s(wrong)< cooldown.

**Comment by Greymane** [comment]
@Ohpala Teu google translator ta ruim ein fi, o problema é o bonus 2p não funcionando?
