### ISSUE TITLE
TOES issues 

### ISSUE THREAD

**Issue by ashruner** [Damieninabox/Lotus-WoW-Bugtracker#267]
**Protector of the endless**
https://www.wowhead.com/spell=117986/defiled-ground the ability gained by kaolan after one of the fish dies doesnt seem to appear at all , its supposed to be spammed very frequently , making the tank on kaolan kiting almost non stop 

**Tsulong**
Aoe fear in dark phases seems to be bigger than displayed , could be due to latency , dark phase debuff  https://fr.wowhead.com/spell=122768/ombres-de-l-effroi doesnt dissapear immediatly when you go in the light beam  https://www.wowhead.com/spell=122789/sunbeam , instead you need to be in the beam when the next tick of it gonna occur for it to dissapear apparently 

edit:it seems that healing done to tsulong while in day phase counts toward night phase aggro table , as a healer i took aggro while day phase ended multiple times , not sure if its a bug but i didnt find anything about healers taking aggro on tsulong in retail mop 

**lei shi**
hunters mark stays visible during the hide , causing some people to be able to melee her , look at the number of attack needed to reveal her aswell cause it felt extremely long compared to some videos , maybe we had a bad comp for it 

**sha of fear**
we dont get the buff https://www.wowhead.com/spell=118977/fearless after killing the adds , this should make the fight extremely hard but its offset by the fact that the timer for https://www.wowhead.com/spell=119593/ominous-cackle is extremely random , on the try where we killed it we dropped the boss to around 45% hp before any tp happened

The adds dont have the correct spray pattern aswell , making it impossible to predict the safezones

**Comment by Damieninabox** [comment]
@Greymane 
https://ibb.co/kDXCqBq
its the spray pattern of the adds on sha of fear

**Comment by Greymane** [comment]
> Protector of the endless
> https://www.wowhead.com/spell=117986/defiled-ground the ability gained by kaolan after one of the fish dies doesnt seem to appear at all , its supposed to be spammed very frequently , making the tank on kaolan kiting almost non stop

First cast corrected to be within 5s, consecutive casts are within 15.5s  according to DBM videos on yt, i will consider this one invalid.

**Comment by Greymane** [comment]
> edit:it seems that healing done to tsulong while in day phase counts toward night phase aggro table , as a healer i took aggro while day phase ended multiple times , not sure if its a bug but i didnt find anything about healers taking aggro on tsulong in retail mop

Intended, healing spells aggro is split evenly between all targets that are in combat with the target you healed.

**Comment by Greymane** [comment]
> look at the number of attack needed to reveal her aswell cause it felt extremely long compared to some videos , maybe we had a bad comp for it.

Checked, the hide aura has 10 stacks and each occurence of damage removes 1 stack, no cooldown between stack removal, working as intended.

**Comment by Greymane** [comment]
> we dont get the buff https://www.wowhead.com/spell=118977/fearless after killing the adds

I [did get the buff](https://puu.sh/J31Bo/3e0d742132.jpg) normally after killing the pandas and teleporting
