### ISSUE TITLE
Spirit Wolf

### ISSUE THREAD

**Issue by Ohpala** [Damieninabox/Lotus-WoW-Bugtracker#268]
**Describe the bug**
Spirit wolf skill has no cooldown

> Speel: https://pt.wowhead.com/spell=51533/espírito-feral
> Npc(Wolf): https://www.wowhead.com/npc=29264/spirit-wolf
> Spell of Wolf: https://www.wowhead.com/spell=58867/spirit-leap

**To Reproduce**

> https://youtu.be/SZmW3i6ia-k

**Additional context**
The wolf skill must have a cooldown of 20s, but it has a 0s cooldown

**Comment by Damieninabox** [comment]
Confirmed, cooldown should be 20 seconds

**Comment by Damieninabox** [comment]
Spell has a 20 second cooldown, gotta dig deeper into this
