### ISSUE TITLE
Dt+Chains of Ice

### ISSUE THREAD

**Issue by Ohpala** [Damieninabox/Lotus-WoW-Bugtracker#269]
**Describe the bug**
When using dk lvl 58 talent, it is possible to pass DT hunter
> Hunter spell: https://mop-shoot.tauri.hu/?spell=19263
> Dk Spell: https://mop-shoot.tauri.hu/?spell=45524
> Talent: https://mop-shoot.tauri.hu/?spell=50041
**To Reproduce**

> https://youtu.be/oenCG4s6YKM

**Additional context**

you can only pass if you are using the talent.

**Comment by Greymane** [comment]
Vey, escreve melhor isso daí, tendi nada kk

**Comment by Ohpala** [comment]
só olhar o video que da pra entender .-.

**Comment by Ohpala** [comment]
depender do google tradutor pra fazer report é foda zzz
