### ISSUE TITLE
Old dungeon | Ragefire Chasm is doubled 

### ISSUE THREAD

**Issue by Missix12** [Damieninabox/Lotus-WoW-Bugtracker#27]
**Describe the bug**
You can find BOTH types of RFC here, both pre and post cata boss are up (except for the demon boss from vanilla).
Also peons npc's do not exist here so you can't complete one quest.

**Comment by Alurienia** [comment]
To add to this. 
![image](https://user-images.githubusercontent.com/37201167/144680356-9c7bbf8b-77fe-429e-98c8-4f8a03b5b684.png)
![image](https://user-images.githubusercontent.com/37201167/144680416-9e96efeb-d806-41bb-874a-22fcee6755e0.png)
