### ISSUE TITLE
Spell of rogue "Detection" doesn't work

### ISSUE THREAD

**Issue by Talbyfirst** [Damieninabox/Lotus-WoW-Bugtracker#273]
**Describe the bug**
For the rogue class, when you apply the minor glyph "Detection", it doesn't appear in your spellbook, so you can't use it.
Link wowhead of the spell : https://fr.wowhead.com/spell=56814/d%C3%A9tection

**To Reproduce**
Everywhere

Problem Description :

You should have that spell and when it works you should have it up for 30 seconds.

**Screenshots**
Problem : https://imgur.com/a/Ca2bkg2
When fixed : https://imgur.com/TRRZW5Q
**Additional context**
X

**Comment by Damieninabox** [comment]
Fixed with next core update
