### ISSUE TITLE
NPCs from quest aren't working 

### ISSUE THREAD

**Issue by jaobre** [Damieninabox/Lotus-WoW-Bugtracker#274]
The quest says to free the Greenstone Miners. Those NPCs should be under rocks and be able to "loot", with loading of 2-3 seconds.
In our case, the NPCs are just laying there. 

![WoWScrnShot_122221_093917](https://user-images.githubusercontent.com/96520862/147065924-222b1e95-c4b8-4e32-8072-efc6d85b31bf.jpg)
![WoWScrnShot_122221_093928](https://user-images.githubusercontent.com/96520862/147065934-3dc745a0-7c11-4413-9a6a-cdd1e268fdcb.jpg)
![WoWScrnShot_122221_095328](https://user-images.githubusercontent.com/96520862/147065935-57a04932-30b9-411a-9ff2-05d9acf4fcae.jpg)

Greenstone Quarry, Jade Forrest
Trapped! Quest

This is the video i've found online, of how it should look like. 
https://www.youtube.com/watch?v=0stIhb15tLc

Unfortunately, I couldn't find again the ones I did already, but one is at the beginning of the cave, at the entrance. 
Gl

**Comment by Damieninabox** [comment]
Fixed with next server update
