### ISSUE TITLE
NPCs aren't dropping the item needed for a quest.

### ISSUE THREAD

**Issue by jaobre** [Damieninabox/Lotus-WoW-Bugtracker#275]
It's said in the report name.
NPCs are Orchard Wasp in Jade Forrest, close to Arboretum
![WoWScrnShot_122221_103823](https://user-images.githubusercontent.com/96520862/147071248-e95f3d95-1fff-40a5-94b0-3aff2bd12cf2.jpg)

Quill of Stingers, Quest

**Comment by Damieninabox** [comment]
Killed 12 of them, was able to finish the quest -> basically invalid report, will adjust the dropchance with next server update

**Comment by jaobre** [comment]
Killed 6 to 10 of them. x_x

Thanks!
