### ISSUE TITLE
Cats have no souls x_x

### ISSUE THREAD

**Issue by jaobre** [Damieninabox/Lotus-WoW-Bugtracker#276]
![WoWScrnShot_122121_162332](https://user-images.githubusercontent.com/96520862/147072933-07360969-43a9-456f-b668-ccd6a9fd63d7.jpg)
![WoWScrnShot_122121_162527](https://user-images.githubusercontent.com/96520862/147072937-07e69d5e-16d1-49e9-b8f2-2e2d4fc111a0.jpg)
![WoWScrnShot_122121_162550](https://user-images.githubusercontent.com/96520862/147072942-31cfd21e-c598-4123-88df-dea83187f768.jpg)

I guess I am here for these simple, small broken things \o/

**Comment by Damieninabox** [comment]
Adjusted with next server update
