### ISSUE TITLE
Ban'thalos Pathing is broken

### ISSUE THREAD

**Issue by sleepyx** [Damieninabox/Lotus-WoW-Bugtracker#278]
https://www.wowhead.com/npc=54320/banthalos  mob's pathing isnt allowing it to come out of the sky making it impossible to tame as a hunter.

**Comment by Damieninabox** [comment]
https://www.wowhead.com/npc=54320/banthalos#comments

He is found circling high above the Sanctuary of Malorne.

Ban'thalos flies up very high. The fall would kill you without some sort of fall slowing mechanism. The best method seems to be to park yourself at the top of the tree just behind the statue of Malorne. Have a freezing trap down. Once he flies close enough, fly up a bit, dismount, shoot and tame.

Coming from the comment section from the link you posted, every retail video I checked also never showed him actually coming down.

Works as intended

**Comment by sleepyx** [comment]
The issue with pathing is once he is engaged in combat he stands still and
refuses to me then resets.
