### ISSUE TITLE
[Quest] The Jade Forest - The Final Blow!

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#284]
**Describe the bug**
Explosives don't disappear when ignited, and no enemies are spawned up the stairs. 

QuestID: 31769

**To Reproduce**
Use flare gun to ignite explosives. 

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/148052671-26a05009-92b0-4d96-880b-54a14c9802cd.png)

**Additional context**
https://www.youtube.com/watch?v=kwZW3SWzBww
Demonstration of how it is supposed to look.

**Comment by Damieninabox** [comment]
Fixed with next server update
