### ISSUE TITLE
[NPC] Dread Wastes - ikthik warriors not attackable

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#288]
**Describe the bug**
Ik'thik Warriors not attackable. They also have some wierd visual phasing issues.
(https://www.wowhead.com/npc=67034/ikthik-warrior)

**To Reproduce**
Go to 50, 42

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/148087807-1a98f76d-2c2d-46e7-ae68-59aefe2513be.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
