### ISSUE TITLE
[Quest] Final Confrontation

### ISSUE THREAD

**Issue by Zube18** [Damieninabox/Lotus-WoW-Bugtracker#289]
**Describe the bug**
Trade Prince Gallywix has x10 HP.
Retail back then was 150k. Here he has 1.5 Mil.

And thrall doesnt have any animations, but he is doing dmg while standing there :)

**To Reproduce**
Start Quest

**Screenshots**
https://youtu.be/lzhIzQLB7uY?t=131 retail
https://imgur.com/a/pFcnnOP server

**Comment by Damieninabox** [comment]
Fixed with next server update
