### ISSUE TITLE
[Quest] Echo Isles - An Ancient Enemy (24814)

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#290]
**Describe the bug**
https://www.wowhead.com/quest=24814/an-ancient-enemy#videos:id=35284

RP with Voljin not implemented. 

**To Reproduce**
Pick up quest and run up the hill to start the fight, Voljin is not in a position to proceed.

**Screenshots**
![image](https://user-images.githubusercontent.com/80163881/148106160-861b3a22-4bda-4533-a3ed-f208b8ee3d29.png)

**Comment by Damieninabox** [comment]
Fixed 6 days ago, just didn't hit the live server yet
