### ISSUE TITLE
Azshara quests

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#296]
Hi,

I was testing Azshara leveling quest and stumbled on this issues : 

Quest https://www.wowhead.com/quest=14469/hand-me-downs requires to travel a landmine near 27.94 / 54.31. The mines when exploding do very little damage. On wowhead comment section about the quest, they are suppose to be deadly. Here I can walk on all the mines without a sweat.
![WoWScrnShot_010522_204240](https://user-images.githubusercontent.com/96208507/148279315-d678b7e1-f9c4-4706-98b0-ce2227fd70ac.jpg)

Quest https://www.wowhead.com/quest=24452/profitability-scouting is suppose to complete itself when arriving near the location. But it doesn't. Tried going around the location and moving everywhere, it doesn't complete the quest. As I cannot complete it I cannot test the rest of the quest chain.
![WoWScrnShot_010522_205339](https://user-images.githubusercontent.com/96208507/148280831-c6fb1f16-11fb-4496-87af-4a01e7093597.jpg)

NPC https://www.wowhead.com/npc=43217/bilgewater-rocket-jockey#comments is suppose to have a dialog to put player in a rocket and follow the circuit to fast travel in Azshara. I guess it is a heavy work to code the rockets. Maybe put the dialog option to teleport the player ? Otherwise we will walk :)
![WoWScrnShot_010522_211227](https://user-images.githubusercontent.com/96208507/148283160-e78e3edc-ec99-4997-9a2d-b6068e2406a5.jpg)

Quest https://www.wowhead.com/quest=14295/sisters-of-the-sea#comments when you click on the stone behind the elite mob to kill, it's suppose to remove the "elite" part so you can kill her without problem. However clicking on the stone has no effect on the mob (combat log on picture).
![WoWScrnShot_010522_214823](https://user-images.githubusercontent.com/96208507/148287600-7e07aa30-ef7e-4988-9bcc-00513768da48.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server update
