### ISSUE TITLE
Azshjara (again :) )

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#297]
Hi there,

For the quest : https://www.wowhead.com/quest=14487/still-beating-heart#comments you are suppose to call a gobelin troop with an item provided : https://www.wowhead.com/item=49629/gob-squad-flare . This helps you deal with the elite mob and loot the quest item. But gobelins don't show so you get to 1v1 the elite and be oneshot.
Still could retrieve the item by using stealth and clicking.

Found a video of it : https://www.youtube.com/watch?v=UDLK6e8c3hY

Quest https://www.wowhead.com/quest=14484/head-of-the-snake as the gobelin team provided by the previous item https://www.wowhead.com/item=49629/gob-squad-flare doesn't show it is impossible to solo the elite to kill.

Cheers

**Comment by Damieninabox** [comment]
Fixed with next server update
