### ISSUE TITLE
Cosmetic | "Grab" Mouse cursor still shows after completing The Lesson of the Burning Scroll | Panda starting

### ISSUE THREAD

**Issue by BottledFart** [Damieninabox/Lotus-WoW-Bugtracker#3]
**Describe the bug**
Completed the above mentioned quest, went onto do The Disciple's Challenge.
Completed it, met Master Shang Xi on the bridge.
Grab cursor is still showing.
**To Reproduce**
Repeat steps mentioned above - cursor should not be showing grab anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/24526201/144664120-82097427-17ff-45c6-9a4a-ceb44eb70b85.png)

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next server update
