### ISSUE TITLE
Ashenvale

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#300]
Hey,

I'm now in Ashenvale and found a minor quest bug : 

- Quest https://www.wowhead.com/quest=13628/got-lumber
when quest is taken the player should be able to click on NPC https://www.wowhead.com/npc=33374/brutusk and ride him to NPC https://www.wowhead.com/npc=33421/gorka . When clicking on Brutus, **the quest gets completed** but the player is not mounted nor taken to Gorka.
![WoWScrnShot_010722_162914](https://user-images.githubusercontent.com/96208507/148566942-5642020d-a2a5-4654-a618-9fe5f347b6ca.jpg)
![WoWScrnShot_010722_163022](https://user-images.githubusercontent.com/96208507/148566949-3b758849-6b4f-4ea8-b714-dbaedca77f6f.jpg)

**Comment by Damieninabox** [comment]
Quest got fixed several days ago, didn't hit the live server yet
