### ISSUE TITLE
[Quests/Inactive NPC] Jerrik Highmountain (Zone: Northern Barrens)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#310]
3 Quests related to NPC Jerrik Highmountain (www.wowhead.com/npc=34626/jerrik-highmountain) are unable for completion as the quest-giver isn't triggering

**Screenshots**
![image](https://user-images.githubusercontent.com/95563818/148913871-39491786-b90b-4116-bafb-7937bed9a259.png)

**Comment by Damieninabox** [comment]
Cant reproduce
