### ISSUE TITLE
[Inactive NPC/Quests] Gazrog (Zone: Ratchet, Northern Barrens)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#311]
NPC not triggering hence cannot turn in and complete following quests from Gazrog (https://www.wowhead.com/npc=3464/gazrog)

![image](https://user-images.githubusercontent.com/95563818/148915791-eaad2938-0acf-4f28-b955-8dd88fdc6365.png)

**Comment by Damieninabox** [comment]
Couldn't reproduce
