### ISSUE TITLE
[Quest] Mutiny, Mon!  (Zone: Fray Island, Northern Barrens)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#312]
Quest (https://www.wowhead.com/quest=14063/mutiny-mon) doesn't work because the trigger (blowing a horn to call forth Tony Two-tusk and his mates) does not work. There shd be a small RP event that leads to final boss Elisha

![image](https://user-images.githubusercontent.com/95563818/148924414-89948bda-32d6-45a3-8f66-7cfdec5b9b9b.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
