### ISSUE TITLE
[Quest] Hezrul Bloodmark (Zone: Lushwater Oasis, N.Barrens)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#315]
Quest (https://www.wowhead.com/quest=852/hezrul-bloodmark) cannot be completed because the boss NPC isn't activated. 
I waited 10 mins and roamed the entire Lushwater Oasis to no avail

How it should behave? The boss Hezrul alongwith 2 of his bodyguards will be patrolling Lushwater Oasis in a clockwise pattern

**Comment by Damieninabox** [comment]
Fixed
