### ISSUE TITLE
[Quest] Got Wood? (Zone: The Mor'Shan Ramparts, Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#316]
Quest (https://www.wowhead.com/quest=13628/got-lumber) _[not sure why it's called 'Got Lumber?' on wowhead must be due to Blizz censorship]_ cannot be completed as Kardak npc is bugged so we can't proceed to ride Brutusk

![image](https://user-images.githubusercontent.com/95563818/148953956-d18c4771-847a-4f4f-af29-859eb3e8d983.png)

**Comment by Damieninabox** [comment]
Got fixed some days ago
