### ISSUE TITLE
[Quest item drop rate] Needs a Little Lubrication (Zone: Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#317]
Quest (https://www.wowhead.com/quest=13651/needs-a-little-oil) _Yea it's blizz censorship_  requires the player to collect 5 Natural Oil (https://www.wowhead.com/item=45071/natural-oil)

WoWhead says their drop rate should be above 30% but I spent nearly 20 minutes killing every slime to end up with my quota of oil. Either my RNG sucks or the drop rate should be buffed

**Comment by Damieninabox** [comment]
Fixed with next server update
