### ISSUE TITLE
[Quest] Crisis at Splintertree (Zone: Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#318]
The quest (https://www.wowhead.com/quest=13653/crisis-at-splintertree) require us to talk to to npc Gorka who will then have us ride on Brutusk (https://www.wowhead.com/npc=34007/brutusk)

However the quest autocompletes without transporting us back to Mor'shan Rampart (it is an epic RP event when I did it on retail. Brutusk goes full rambo mode and squishes those filthy elves)

The side-effect of this autocomplete is that now in order to return to Mor'shan Rampart there's just way too many hostile npcs for a leveling toon to deal with :) Lucky for me I was a druid so i stealthed through so R.I.P non-stealth classes

![image](https://user-images.githubusercontent.com/95563818/148958178-1b520dda-efcf-4b90-9404-78c3ed6dcd84.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
