### ISSUE TITLE
[Quest] To the Rescue! (Zone: Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#319]
Quest (https://www.wowhead.com/quest=13712/to-the-rescue) is bugged hence cannot start/complete it

![image](https://user-images.githubusercontent.com/95563818/148959227-82bdeb30-c5c9-40a3-a842-3cf011ed2aff.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
