### ISSUE TITLE
[Game Object] Mail Expiry only 24 hours??

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#320]
A mail to me from my riding trainer is set to expire in a day. As per wowpedia mail expiry is 30 days. Bug?

![image](https://user-images.githubusercontent.com/95563818/148961774-108a3c4b-245c-4bb1-9a78-93ab81337af0.png)

**Comment by Greymane** [comment]
Creature-sender mails (flight masters, bg tokens, etc) are expected to expire in 24 hours, no bug here.
