### ISSUE TITLE
[Quest/Inactive NPC] Destroy the Legion (Zone: Splintertree Post, Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#321]
Quest (https://www.wowhead.com/quest=26448/destroy-the-legion) cannot be completed as npc Durak is not triggering

![image](https://user-images.githubusercontent.com/95563818/148962703-a73bc74c-06fd-4fa7-9877-76e8fee62653.png)

**Comment by Damieninabox** [comment]
https://www.wowhead.com/quest=26448/destroy-the-legion quest even says that starter and ender is "Valusha" -> works properly in game
