### ISSUE TITLE
[Inactive NPC] Guardian Gurtar (Zone: just past Warsong Lumber Camp, Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#324]
Quest-giver Gurtar (https://www.wowhead.com/npc=34242/guardian-gurtar) is inactive hence unable to complete quest
![image](https://user-images.githubusercontent.com/95563818/148982632-29d7100e-16bf-4663-8a0d-fbdb96abeafa.png)

**Comment by Damieninabox** [comment]
Fixed with next update, required pre quest is [13873 ](https://www.wowhead.com/quest=13873/sheelahs-last-wish)
