### ISSUE TITLE
[Quest] Bad News Bear-er

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#325]
Quest (https://www.wowhead.com/quest=13848/bad-news-bear-er) should open up a dialogue option with npc Vhulgra  who will then send you to destination quest hub. 

Bug: Vhulgra has no dialogue options and just opens up regular flight map (not as part of the quest trigger)

![image](https://user-images.githubusercontent.com/95563818/148988955-978033ab-00f7-430a-b2cf-eb36f4560fbf.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
