### ISSUE TITLE
Druid spell : Wild Charge

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#327]
Hey,

There is something a bit weird with the [Wild Charge](https://www.wowhead.com/spell=49376/wild-charge).
When used on a target facing me, it doesn't put me behind the target. When target is facing away from me on the other hand there is no problem.
Stealth doesn't change anything.

![WoWScrnShot_011122_231617](https://user-images.githubusercontent.com/96208507/149031069-66bb20af-29f0-4656-ba81-704dc36b03bd.jpg)

https://youtu.be/PQzON7nEn2s

**Comment by Greymane** [comment]
It IS putting you behind the target, the bug lies in the fact it doesnt auto-turn your character towards the back of the enemy. Will fix it regardless.
