### ISSUE TITLE
[Zone] Zoram'gar Outpost, Ashenvale

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#328]
1) Quest  Vorsha the Lasher (https://www.wowhead.com/quest=6641/vorsha-the-lasher) RP event is completely missing the only way you can complete the quest is to manually kill the final boss

2) beast npc Mystlash Hydra (https://www.wowhead.com/npc=3721/mystlash-hydra) respawn time needs to be buffed. All other creatures needed for quests are respawning quickly but this hydra takes way too long hence delaying quest progress significantly

3) Quest (https://www.wowhead.com/quest=13923/to-hellscreams-watch) dialogue option for flightmaster Andruk missing. He just opens flight map not as part of quest progress

![image](https://user-images.githubusercontent.com/95563818/149167347-b1c7140f-c6e9-445c-9170-d22975d07ed0.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
