### ISSUE TITLE
[Quest] Blastranaar! (Zone: Hellscream's Watch, Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#329]
Quest (https://www.wowhead.com/quest=13947/blastranaar) cannot be completed as the bombing run has to be triggered by Flightmaster Thraka but she's not showing the required dialogue option just regular Flight map unrelated to quest

![image](https://user-images.githubusercontent.com/95563818/149172421-74c091d1-9474-4801-9382-1b71f557a8f9.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
