### ISSUE TITLE
[Quest] Vortex (Zone: Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#330]
Quest (https://www.wowhead.com/quest=13888/vortex) is bugged. 
Even though the RP event triggers and you become one with the wind elemental gaining his abilities the boss npc doesn't take any damage and the event end on its own. The screenshot shows me having being returned to quest giver and having to do it again. Tried 3 times
![image](https://user-images.githubusercontent.com/95563818/149187503-134887dc-a755-4564-9f61-c2e95ccd108b.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
