### ISSUE TITLE
[Quest] Shadumbra's Head (Zone: Ashenvale near Raynewood Retreat)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#331]
Quest (https://www.wowhead.com/quest=24/shadumbras-head) cannot be completed because the event finishes too fast (<1 second). She is supposed to be in battle with the warsong guards for us to kill her and loot her head 
**Bug:** Here on Lotus she just spawns and dies in 1 hit to the orc npc

Screenshot shows me literally on top of her spawn point lying in wait but she got insta-killed as soon as she spawned 
![image](https://user-images.githubusercontent.com/95563818/149211203-cf5e022d-9f13-49fd-a90b-cb66f8a801ab.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
