### ISSUE TITLE
[Inactive NPC] Blood Guard Aldo Rockrain (Zone: Silverwind Refuge, Ashenvale)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#332]
NPC has to start this Quest (https://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two) but quest trigger is not active 
![image](https://user-images.githubusercontent.com/95563818/149387997-49600de2-42d0-4ab4-9f8b-84bc0604d5b0.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
