### ISSUE TITLE
[NPC] Krom'gar Wagon  (vehicle npc from Ashenvale to Stonetalon Peak)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#333]
This NPC (https://www.wowhead.com/npc=41744/kromgar-wagon) has the following bugs: 

1) Movespeed is way too slow (my druid cat form is faster than it). Could be an optical illusion to me but it seems as if the wagon's wheels were moving faster but the vehicle itself wasn't corresponding to that movespeed

2) Wagon clips into the ground at some points of it's pathing

It's not gamebreaking but you wanted me to note everything that isn't blizzlike :)

**Comment by Damieninabox** [comment]
Fixed with next restart
