### ISSUE TITLE
[Inactive NPC] Saurboz (Zone: Stonetalon Mountains)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#334]
It's related to Github #332 since Saurboz is the end npc of that questchain

Hence unable to start this Quest (https://www.wowhead.com/quest=25999/barrier-to-entry)

![image](https://user-images.githubusercontent.com/95563818/149390040-849a284c-09f5-4702-8f8b-fdc63285012a.png)

**Comment by BanHammer69** [comment]
Addendum: He's needed for turning in and starting other quests too so yea fixing him would fix the quest chains too.

**Comment by Damieninabox** [comment]
Can't reproduce
