### ISSUE TITLE
[Inactive NPC] Blastgineer Fuzzwhistle

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#335]
NPC( https://www.wowhead.com/npc=40901/blastgineer-fuzzwhistle) is inactive hence can't start his quest

![image](https://user-images.githubusercontent.com/95563818/149400631-aad56254-ffb6-4369-a33f-71091d482ea6.png)

**Comment by Damieninabox** [comment]
Can't reproduce, neither on local nor on live server
