### ISSUE TITLE
[Enemy NPCs inactive] Quest -Seek and Destroy (Zone: Stonetalon Mountains)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#336]
Quest (https://www.wowhead.com/quest=26009/seek-and-destroy) requires you to kill 20 Alliance npcs. 
Majority of the gnomes despite being marked hostile will not attack you hence cannot be attacked either towards quest completion.
![image](https://user-images.githubusercontent.com/95563818/149445614-e0890195-d0ea-40b8-a47c-985e6aa6a105.png)

**Comment by BanHammer69** [comment]
Weapon npc (https://www.wowhead.com/npc=41895/goblin-heavy-gun) cannot be interacted with + it's in 2 different trigger states simultaneously so you cannot use them to kill Gnomish Bomber enemy NPC thereby not counting toward quest progress

![image](https://user-images.githubusercontent.com/95563818/149446702-c4d39226-0be2-4e89-877b-6c24492370ba.png)

**Comment by Damieninabox** [comment]
Adjusted with next server update
