### ISSUE TITLE
[Quests inactive] NPC: Overlord Kromgar (Zone: Stonetalon Mountains)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#337]
1) Related to github #334 you cannot complete quest (https://www.wowhead.com/quest=26004/kromgar-fortress) since you were unable to accept the breadcrumb starter

2) Unable to accept quest (https://www.wowhead.com/quest=26010/ashes-to-ashes)
![image](https://user-images.githubusercontent.com/95563818/149447362-265be42c-23b2-4d88-8983-f86c325105cc.png)

**Comment by BanHammer69** [comment]
3.Unable to accept quest (https://www.wowhead.com/quest=26020/report-to-bombgutz)
![image](https://user-images.githubusercontent.com/95563818/149449366-ac9095d1-4c59-4c55-b9c8-361d799cabd7.png)

**Comment by BanHammer69** [comment]
4. Unable to accept quest (https://www.wowhead.com/quest=26059/eyes-and-ears-malakajin) since it follows the end of the entire quest chain detailed in #338 
![image](https://user-images.githubusercontent.com/95563818/149497520-4af65e60-d543-46b9-9435-e791c0fb990d.png)

**Comment by Damieninabox** [comment]
Cant reproduce 2.0
