### ISSUE TITLE
[Inactive NPC/quests] Blastgineer Bombgutz (Zone: Stonetalon Mountains)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#338]
1) Has breadcrumb dependency on #337 for quest (https://www.wowhead.com/quest=26020/report-to-bombgutz)

2) Unable to accept quest (https://www.wowhead.com/quest=26044/where-are-the-parts)
![image](https://user-images.githubusercontent.com/95563818/149463610-f73c2b5a-5ab8-4dfd-8df8-71cf2fe0c73d.png)

**Comment by BanHammer69** [comment]
Due to above unable to proceed with following quest (https://www.wowhead.com/quest=26045/i-got-your-parts-right-here)

![image](https://user-images.githubusercontent.com/95563818/149495161-5dee16dd-fcae-45de-8c27-fcde2693fdd7.png)

**Comment by BanHammer69** [comment]
Unable to proceed with Quest (https://www.wowhead.com/quest=26047/and-thats-why-they-call-them-peons)
![image](https://user-images.githubusercontent.com/95563818/149495733-7cf98f9e-8888-4023-b420-600d5ee616df.png)

**Comment by BanHammer69** [comment]
Unable to proceed with Quest (https://www.wowhead.com/quest=26046/between-a-rock-and-a-hard-place)
![image](https://user-images.githubusercontent.com/95563818/149495975-49aba195-0991-482f-b5ac-c9378b33dd59.png)

**Comment by BanHammer69** [comment]
Unable to proceed with Quest (https://www.wowhead.com/quest=26048/spare-parts-up-in-here)
![image](https://user-images.githubusercontent.com/95563818/149496289-e83230f7-0361-4f37-9d5e-4d0482947777.png)

**Comment by BanHammer69** [comment]
Unable to proceed with Quest (https://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress)
See also #336 for comment on Goblin Heavy gun that needs to be fixed in order to complete this quest
![image](https://user-images.githubusercontent.com/95563818/149496830-0bc68c0b-3b44-4ec5-b057-fb0ded1924cd.png)

**Comment by Damieninabox** [comment]
Can't reproduce any inactive npc issue, not on our local systems nor on the live server
