### ISSUE TITLE
Minor npc bug in Hinterlands

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#339]
**Minor npc bug** npc https://www.wowhead.com/npc=42592/the-direglob doesn't fight back when engaged in combat
![WoWScrnShot_011622_164512](https://user-images.githubusercontent.com/96208507/149667151-08b97477-85cb-4d1f-8cc4-455b1bde10b6.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server restart
