### ISSUE TITLE
Loch Modan - Inn Keeper not an Inn Keeper

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#344]
**NPC** https://www.wowhead.com/npc=1156/vyrin-swiftwind is suppose to be an Innkeeper but she doesn't offer the possibility
![WoWScrnShot_011822_000743](https://user-images.githubusercontent.com/96208507/149846217-d093b623-1628-417e-af94-ec206bed7529.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server update
