### ISSUE TITLE
Loch Modan - NPC Bingles Blastenheimer

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#346]
- **NPC** https://www.wowhead.com/npc=6577/bingles-blastenheimer
After turning in quest https://www.wowhead.com/quest=27031/wing-nut I can't open the chat with the NPC to take the next quest. It reacts as if there is nothing to be done with him.
![WoWScrnShot_011822_002741](https://user-images.githubusercontent.com/96208507/149847419-ccf6d57b-f3bf-4be5-be62-5e9d7028a4bf.jpg)

**Comment by Damieninabox** [comment]
Can't reproduce, could accept "Bird is the Word" without issues
