### ISSUE TITLE
Spirit Rez Healer

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#347]
When I rez myself through the Spirit Healer, my gear is affected but I don't get the 10min debuff.
![WoWScrnShot_011822_004714](https://user-images.githubusercontent.com/96208507/149848647-7c448af8-e451-4896-ab8a-1511c07a047f.jpg)

![WoWScrnShot_011822_004757](https://user-images.githubusercontent.com/96208507/149848651-79d7a0fd-4fea-4c99-871c-499b3f0e4b39.jpg)

**Comment by Damieninabox** [comment]
Intended during the beta, sickness debuff got removed
