### ISSUE TITLE
Wetlands NPC

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#348]
- **NPC** https://www.wowhead.com/npc=1239/first-mate-fitzsimmons is missing and with him the quests he offers
![WoWScrnShot_011822_005255](https://user-images.githubusercontent.com/96208507/149848860-bbee5de2-3fbf-4d40-b722-0a9fd6e88196.jpg)

**Comment by Damieninabox** [comment]
Fixed with next update
