### ISSUE TITLE
Lfg doesn't work

### ISSUE THREAD

**Issue by TobiHome** [Damieninabox/Lotus-WoW-Bugtracker#35]
Lfg doesn't work. Can't que in anyway that should be possible. Same with lfr. Gray button that can't be clicked.

![nowrd](https://user-images.githubusercontent.com/95509204/144687285-ffc2d164-1a3b-42c1-8e59-40876a083973.jpg)

**Comment by Damieninabox** [comment]
Player was in a group while not being the leader of the group -> no bug
