### ISSUE TITLE
Ashenvale - Quest 

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#354]
- **Quest** https://www.wowhead.com/quest=6641/vorsha-the-lasher#
When picked up quest gets instantly completed
![WoWScrnShot_011922_172054](https://user-images.githubusercontent.com/96208507/150171903-6a1f993f-4abb-407c-b42c-f1922a9bd9e1.jpg)

**Comment by Damieninabox** [comment]
Intended for now, will require movement debugging, its on our list
