### ISSUE TITLE
Ashenvale - Quest Freedom to Ruul

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#355]
- **Quest** https://www.wowhead.com/quest=6482/freedom-to-ruul
It's suppose to be an escort quest, however when picked up it's automaticly completed.
![InkedWoWScrnShot_011922_173547_LI](https://user-images.githubusercontent.com/96208507/150174503-5277c255-1f83-4121-9cd0-199073265ff6.jpg)

**Comment by Damieninabox** [comment]
Fixed with next update
