### ISSUE TITLE
Stonetalon Mountains - Quest We're Here to Do One Thing, Maybe Two

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#356]
- **Quest** https://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two
Can complete the quest as [Saurboz](https://www.wowhead.com/npc=34341/saurboz) doesn't let me.
Sadly as it's the first quest of the region I can't pick any other.
![WoWScrnShot_011922_174423](https://user-images.githubusercontent.com/96208507/150175980-c769ebf6-4a63-46c3-ace9-11843b60593d.jpg)

Here a video of it on lotus https://youtu.be/rKajRs5KwSI

**Comment by sleepyx** [comment]
Was able to complete it by doing the quest twice without dropping it.
