### ISSUE TITLE
Minor NPC bug : Gan'zulah doesn't fight back

### ISSUE THREAD

**Issue by aleszel** [Damieninabox/Lotus-WoW-Bugtracker#359]
- Minor NPC bug : https://www.wowhead.com/npc=1061/ganzulah
Doesn't fight back when engaged in combat.
![WoWScrnShot_012022_153334](https://user-images.githubusercontent.com/96208507/150366273-4becdffa-f165-47c8-bba5-71b47bf58cdb.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server update, also added proper combat AI
