### ISSUE TITLE
[Spells][Druid] Wild Charge (Travel Form)

### ISSUE THREAD

**Issue by ManneN1** [Damieninabox/Lotus-WoW-Bugtracker#362]
**Describe the bug**
When using Wild Charge from Travel Form the spell is incredibly buggy.

1. When using it to leap in a different direction than you are going it often doesn't really work at all (goes in the wrong direction) and if it does it snaps the character in a really weird way. It seems that it's not really keeping up with the direction you're currently facing (especially if you're mid-jump).
2. When using Wild Charge when falling, you lose all moment and turn 180 degrees. If you had zero forward momentum when falling the Wild Charge does nothing at all.

**To Reproduce**
1. Learn Wild Charge on a Druid
2. Go Travel Form

3a. Use Wild Charge while falling. You will either do a 180 or nothing at all based on whether you had any forward momentum or not.

3b. Run in one direction, jump, change direction quickly with right mouse button, quickly use Wild Charge -> you'll go in the wrong direction (if you were really fast you'll even go in the initial direction prior to the jump)

PS: 3b. Is just an easy way to reproduce it, but it happens basically all the time when you change direction quickly and use Wild Charge quickly afterwards.

**Screenshots**
https://youtu.be/6JLuKTLchAk : As you can see the camera and character snaps around a lot, it's really jerky and not blizzlike at all
https://youtu.be/KqLPkTJahFY : (Aerial) As you can see I do a 180 here for no reason
https://youtu.be/1Zx_zZrtYgw & https://youtu.be/-RjtpPQWGuY : As you can see the charge doesn't go where I am currently "facing" using the right-mouse button. Especially obvious in the second video.

It's not Blizzlike at all.

**Additional context**
Wild Charge (Travel Form) works 100% correct on some unnamed competitor of yours that just launched, you could compare on there. However, it does not work well on other forms there (so don't just copy it blindly :) ).

Wild Charge (Travel Form) also never changed on retail so you could go there and check how it works as well.

**Comment by ManneN1** [comment]
Also just noticed that Wild Charge (Travel Form) behaves really strange around objects, not jumping over them or into them using the normal trajectory but rather adjusting the jump (?) and getting stuck / stopping in front of them. Not blizzlike at all.

**Comment by Greymane** [comment]
Tried to work aroun it a bit, but it's still not perfect, client just dont like to spam orientation update packets while you are jumping it seems.
