### ISSUE TITLE
[Spells][Druid] Wild Charge (Cat Form)

### ISSUE THREAD

**Issue by ManneN1** [Damieninabox/Lotus-WoW-Bugtracker#363]
**Describe the bug**
Wild Charge, when used in Cat Form, does nto turn the Druid to face the back of the target as expected.

**To Reproduce**
1. Face the front of an enemy (20y away or som
2. Use Wild Charge while in Cat Form
3. You will not be facing the enemies back, but rather 180 degrees away from them.

Note: This works from any direction. You will face the same direction that you pounced towards them from, not into the enemy's back.
**Screenshots**
![image](https://user-images.githubusercontent.com/16864855/150393256-8e5fab95-062c-40eb-9c62-3744b462956d.png)

**Comment by Damieninabox** [comment]
Got fixed today and will work with the next update, check for duplicates first

**Comment by ManneN1** [comment]
I did check for duplicates, and there was no open ticket for this.

**Comment by Damieninabox** [comment]
Because it was closed since it got fixed

**Comment by ManneN1** [comment]
And why would you close something before it's actually live?

Reporters aren't going to go through _closed_ tickets before reporting a _current_ issue. Also, bugs regress.

**Comment by Damieninabox** [comment]
Because I will 
1) not restart the server after every fix
2) leave already solved issues open to create an entire mess on github

We will get rid of the github bugtracker once the new CMS is online anyways

No need to discuss this further
