### ISSUE TITLE
[Quest] Crossroads Caravan Pickup

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#364]
Cannot start quest (https://www.wowhead.com/quest=13949/crossroads-caravan-pickup) since the dialogue option isn't triggering for the RP event to commence
![image](https://user-images.githubusercontent.com/95563818/150399425-d961553a-e392-4fe1-96e8-eec5bd596e8e.png)

**Comment by Damieninabox** [comment]
Duplicate
