### ISSUE TITLE
[Quest] We're Here to Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by SasquatchFiesta** [Damieninabox/Lotus-WoW-Bugtracker#365]
![WoWScrnShot_012022_205422](https://user-images.githubusercontent.com/45911989/150457773-882732cf-7f95-46b8-bf38-7fbfcd32d9f0.jpg)
stuck in the Krom'gar Caravan Wagon, re-logging does not help, can not use unstuck features in game. Had to be killed to get out of caravan.

It also sucks you in if you are near it, would not be too bad if you were able to dismount it, but you can't currently https://youtu.be/0TYepEuV0PY

**Comment by sleepyx** [comment]
Theres a few of these wagons on the road sucks in both alliance and horde

**Comment by SasquatchFiesta** [comment]
Same issue as #356, when the caravan did work properly(used the proper caravan which , [worked 1 of 3 times, had to relog for that one](https://www.youtube.com/watch?v=HUHEG7d07Sg) was unable to complete as well. It seems like when clicking the back of the wagon im stuck like in the video, but clicking the Kodo taxis me to stonetalon.

Running back and retaking the caravan again seems to complete the quest, sometimes. I did it twice and still not complete, Sleepy's quest completed the second time.

**Comment by Damieninabox** [comment]
Fixed
