### ISSUE TITLE
[Quest] Threat from the Water (Zone: Darkshore)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#366]
Quest (https://www.wowhead.com/quest=13522/threat-from-the-water) is not available for pickup from the NPC. She's showing another quest instead
![image](https://user-images.githubusercontent.com/95563818/150559694-d8caa058-0989-4f42-9b3e-e2bf1a37e4e8.png)

**Comment by Damieninabox** [comment]
Fixed with next update
