### ISSUE TITLE
[Inactive NPCs & Quest] The last wave of survivors (Zone: Darkshore)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#367]
NPC Volcor (https://www.wowhead.com/npc=32960/volcor) is supposed to give us the quest (https://www.wowhead.com/quest=13564/a-lost-companion) but his dialogue box doesn't have it

He is also part of another quest chain (https://www.wowhead.com/quest=13518/the-last-wave-of-survivors) that involves the below NPCs too
![image](https://user-images.githubusercontent.com/95563818/150560833-02fd81fa-8a4a-41b0-871d-1de54f700fb5.png)

**Comment by BanHammer69** [comment]
Same for Gershala (https://www.wowhead.com/npc=32911/gershala-nightwhisper) who hand us another quest
![image](https://user-images.githubusercontent.com/95563818/150561220-8f2fb0fb-d163-4b09-ab1f-27c5c7a109f5.png)

**Comment by BanHammer69** [comment]
Same for Cerellean (https://www.wowhead.com/npc=33093/cerellean-whiteclaw) who's part of the above quest chain
![image](https://user-images.githubusercontent.com/95563818/150561577-0933acdd-051e-4ddf-bc13-e0c453dd4a4f.png)

**Comment by BanHammer69** [comment]
Same for Shaldyn(https://www.wowhead.com/npc=33095/shaldyn) who's the last survivor that needs rescuing as part of above quest
![image](https://user-images.githubusercontent.com/95563818/150561909-29d51770-b446-49e0-963e-abc46a4dea6a.png)

**Comment by BanHammer69** [comment]
As per Damien instruction I disable Zygor leveling guide and all other addons except Elvui and went back to Volcor but I get same result :(
![image](https://user-images.githubusercontent.com/95563818/150563336-504a9b12-ca73-4217-b248-707282d976ac.png)

**Comment by Damieninabox** [comment]
You get the result for all of the npcs, because they are not supposed to give you quests. The entries in the game and the questgiver entry on wowhead does not match, once you finish "The Last Wave of Survivors", head back to Lor'danel you will then get phased and see the proper questgiver npcs -> entire report is invalid
