### ISSUE TITLE
Quest | Begin Your Training: Master Cheng - level 71 instead of 20

### ISSUE THREAD

**Issue by SasquatchFiesta** [Damieninabox/Lotus-WoW-Bugtracker#376]
Begin Your Training: Master Cheng (31834), Master Cheng (66258) has about 2.7k health and is level 20 before challenging. Once challenged he walks with me with ID:66138 as a random level. I've gotten lvl 71, 32, and 63 in the 3 times ive challenged him, his health is comparable to his level but his damage output is around a level 20.

![WoWScrnShot_012222_212230](https://user-images.githubusercontent.com/45911989/150663695-a81cbb7c-0479-4af9-a72c-e1f8783eb1d9.jpg)
![WoWScrnShot_012222_212921](https://user-images.githubusercontent.com/45911989/150663697-f0481e4b-50e7-4c08-99b1-1250a13182ce.jpg)
![WoWScrnShot_012222_212934](https://user-images.githubusercontent.com/45911989/150663698-29ba43ff-1d7a-4fde-b605-a5a9f17b5e7d.jpg)

![WoWScrnShot_012222_213225](https://user-images.githubusercontent.com/45911989/150663699-2bb149b9-7cd1-451e-aeb3-cc35a9994de5.jpg)

**Comment by SasquatchFiesta** [comment]
when doing 'Practice Makes Perfect: Master Cheng', his daily this is also an issue, as a level 32, i challenged him and CHeng (66138) is level 85
![WoWScrnShot_012222_220636](https://user-images.githubusercontent.com/45911989/150664417-d31ae2d8-53dc-410d-9b32-21cb22c7ea18.jpg)

**Comment by Damieninabox** [comment]
Fixed with next update
