### ISSUE TITLE
Hunter Pet Bug (sending Pet to Creature)

### ISSUE THREAD

**Issue by Lodric48** [Damieninabox/Lotus-WoW-Bugtracker#378]
**Describe the bug**
I found out hunter pets can't always attack targets, it may have something to do with that mmap thingy (not sure)

**To Reproduce**
1. Create a bloodelve hunter as an example
2. levelup enough to activate the  Pet "attack Button"
3. Push the Button and let your pet attack a Lynx
4. your Pet won't move

A more easy Way to reproduce this Bug:

In Dreadwastes for example NPC: https://www.wowhead.com/npc=66465/ikthik-clutch-guard

Stand a bit away and send your Pet. You will see the Pet won't move also if you range attack as a Hunter (dunno if other classes face the same Problem) NPC: 66465 he won't chase you.

**Screenshots**

**Additional context**
I'm not sure if this happen somewhere else but it looks globally depend on Maps i guess

**Comment by Greymane** [comment]
Invalid/Couldn't reproduce, pet was on Assist Mode and as soon as my hunter started ranged attacking the npc, the pet moved to attack, npc 66465 and he also reacted to aggro.
