### ISSUE TITLE
2º wing on black temple raid is close

### ISSUE THREAD

**Issue by Mx-mp4** [Damieninabox/Lotus-WoW-Bugtracker#379]
**Describe the bug**
I was going to farm BT from tbc in order to get tmog+warglaives but after cleared all the first boss zone the door to the next zone still close so i cant continue the raid
**To Reproduce**
Black temple, shadowmoon valley
Door bug
The door is close 
The door should be open to continue the raid

**Screenshots**
![WoWScrnShot_012922_120709](https://user-images.githubusercontent.com/95622972/151658821-641b9cfb-a191-475d-803e-0b944b653369.jpg)

**Additional context**

**Comment by Greymane** [comment]
Damien shut down all pve dungeon/raid related content on the pvp server.

**Comment by Damieninabox** [comment]
We will enable old raid content step by step, starting with Black Temple after the host swap today. Make sure to recheck it then
