### ISSUE TITLE
Guild issue

### ISSUE THREAD

**Issue by HyperionDread** [Damieninabox/Lotus-WoW-Bugtracker#38]
So Prime created the guild, and after guild leader logged off we no longer were "in the guild" while still been receiving guild achievment notifications, guildies loggind, etc.
![WoWScrnShot_120421_023051](https://user-images.githubusercontent.com/62250720/144691991-5e08826c-a56a-4879-a023-0bd881436bb4.jpg)

**Comment by Anakia69** [comment]
Dupplicate. https://github.com/Damieninabox/Lotus-WoW-Bugtracker/issues/9#issuecomment-985942859

**Comment by Damieninabox** [comment]
Duplicate
