### ISSUE TITLE
Quest givers

### ISSUE THREAD

**Issue by sleepyx** [Damieninabox/Lotus-WoW-Bugtracker#381]
Kurong Caskhead-64047 upstairs inn at shrine of two moons. Gives both quest (Stranger in a Mysterious land) -[31488] and [31489]. 31489 is rogue only i believe https://www.wowhead.com/quest=31489/stranger-in-a-strange-land

Sunwalker Dezco- 64566 has both Meet the scout [32249] and Thunder calls [32678] available. Thunder calls is for TOT https://www.wowhead.com/quest=32678/thunder-calls

Flash of Bronze- 33230 available as soon as you leave shrine. added in 5.4 https://www.wowhead.com/quest=33230/a-flash-of-bronze
Will update when i can log in

**Comment by Damieninabox** [comment]
Fixed
