### ISSUE TITLE
List of extra npc

### ISSUE THREAD

**Issue by sleepyx** [Damieninabox/Lotus-WoW-Bugtracker#382]
Shrine of two moons: 
Garrosh hellscream- 67840 is upstairs near portals with a quest available. he shouldnt be here until much later 5.3 i believe.
Honor guard-68293 also in portal room and shouldnt be there
Ishi-67846 portal room shouldnt be there
Beige Sugar- 65859 portal room shouldnt be there.

All t16 vendors should not be there. upstairs opposite side of inn near the bank.

Miss Jadepaw- 73422 or Vanaris Whitesong - 64064 Downstairs of bank. Both are jewelcrafting supplies but only one should be there- SF has miss jadepaw on vanaris's location.

Horde peacekeeper-64587 theres a few scattered around main hall downstairs. Should not be there.
 Will update more as i find them

**Comment by Damieninabox** [comment]
Adjusted
