### ISSUE TITLE
The Source of Our Livelihood

### ISSUE THREAD

**Issue by arianii0** [Damieninabox/Lotus-WoW-Bugtracker#4]
**Describe the bug**
Near Delivery Cart Tender should stand cart which should take us to the city

**To Reproduce**
There is no way to reproduce this bug because there is no cart to use

**Screenshots**
![image](https://user-images.githubusercontent.com/24772087/144664552-bfc2eab1-4efd-4e40-a112-23fce7ab7005.png)

**Additional context**
(https://www.wowhead.com/quest=29680/the-source-of-our-livelihood)

**Comment by Damieninabox** [comment]
Fixed with next restart
