### ISSUE TITLE
Cart Missing To Take You To The Dai-Lo Farmstead For Quest: The Source of our Livelihood

### ISSUE THREAD

**Issue by Ohnage** [Damieninabox/Lotus-WoW-Bugtracker#40]
There is supposed to be a cart you can hop in that takes you to the Dai-Lo- Farmstead. Here is the loction its supposed to be per wowhead. 
![image](https://user-images.githubusercontent.com/5816512/144698208-4c304708-3b04-409b-85e7-9e58ae06a48a.png)

Here is me standing on the location.
![image](https://user-images.githubusercontent.com/5816512/144698178-783bc476-fdbe-44cd-958a-896352b6d828.png)

This makes it so you're unable to progress the zone as its a required quest in the Pindarian storyline.

**Comment by Damieninabox** [comment]
Fixed with next restart
