### ISSUE TITLE
Quest | Smoke Before Fire (Alliance - Pandaria Jade Forest)

### ISSUE THREAD

**Issue by Fexer** [Damieninabox/Lotus-WoW-Bugtracker#41]
**Describe the bug**
During the quest Smoke Before Fire, you need to use the Alliance Flare (Quest Item) and throw it at different targets, there is an issue where no matter the positionning for the Wild Imps, the event never triggers, and we are unable to complete the quest

**To Reproduce**
Twinspire Keep
Whenever throwing the Alliance Flare at the Wild Imps, it doesn't trigger completion
Throwing the alliance Flare at the wild imps should trigger completion

I tried dropping the quest and taking it again, same issue when heading straight for the imps

**Comment by Damieninabox** [comment]
Quest worked -> dummy was too far away, adjusted spawn location
