### ISSUE TITLE
Karr the Darkener 

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#42]
**Describe the bug**
Fight is not as it should be.
Karr currently has 2 phases. He has a phase in which he just melees and casts Shadowbolt and a second phase where he spam will just about only cast Shadow Bolt and Void Cloud.

He also has a casts "Unstable Serum which he should NOT have. https://www.wowhead.com/spell=127373/unstable-serum#used-by-npc this is the same spell ID, spell is also counted as a buff aura and not in the debuff auras. 

His Ancient Guardian pet is also not tied to him and you can pull separately from range. 

Also immune to stun (Fist of Justice only stun tried) 
https://youtu.be/gpxsCJJ56C0?t=10 - Shows stun being used and him being stunned.

Example Fights:
https://www.youtube.com/results?search_query=Karr+the+Darkener
https://www.youtube.com/watch?v=DO_Hb7hFmkY

**To Reproduce**
Steps to reproduce the behavior: Fight him
Location - Dread Wastes - Terrace of Gurthan
Name, Type
Problem Description
How it should work - He should have 1 phase where he casts Void Cloud throughout the fight sparingly and casts shadow bolt, and should be unstable. Should not cast Unstable Serum as well.

**Comment by Damieninabox** [comment]
Fixed with next server update
