### ISSUE TITLE
Dreadspinner Egg attacks!

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#43]
**Describe the bug**
Dreadspinner Egg can attack players.

**To Reproduce**
Steps to reproduce the behavior: Attack Dreadspinner Egg
Location - Dread Wastes - Terrace of Gurthan
How it should work - Should not attack players - be a helpless NPC

https://www.wowhead.com/npc=62077/dreadspinner-egg

**Comment by Damieninabox** [comment]
Fixed with next server restart
