### ISSUE TITLE
[Dungeon] DM-West Tsu'zee

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#45]
**Describe the bug**
Rare Mob "Tsu'zee" is hitting for 2.5k white and 2.5k special. Resulting in 5k instant Tank Death. Seems to high.

**To Reproduce**
Location: DM-West
Name, Type: Tsu'zee, Rare Mob, Rogue
Problem Description: dmg numbers to high

**Comment by Damieninabox** [comment]
Adjusted damage

**Comment by Yalinar** [comment]
seems still to high, he is fast hitting 1.8k. couldnt tank it.
