### ISSUE TITLE
Quest | Only the Worthy Shall Partake

### ISSUE THREAD

**Issue by RemoteDefinition** [Damieninabox/Lotus-WoW-Bugtracker#5]
**Describe the bug**
Master Li Fei the quest mob you need to defeat is friendly rather than unfriendly when you need to defeat them.

Since you can't defeat them you are no longer able to progress through the Pandaren storyline.

**To Reproduce**
Follow the Pandaren Race Quest Line to Shrine of the Inner Light where you will receive the quest from Master Li Fei. There'll be a quest before this one where you light the braziers. For this quest, Master Li Fei will toss you to the center of the ring and will appear.

**Screenshots**
https://prnt.sc/21lg7mv

**Additional context**

**Comment by BottledFart** [comment]
Got the the same place and experiencing it also

**Comment by Damieninabox** [comment]
Fixed with next restart
