### ISSUE TITLE
% sign missing from buff

### ISSUE THREAD

**Issue by TheRealRickle** [Damieninabox/Lotus-WoW-Bugtracker#50]
**Describe the bug**
A clear and concise description of what the bug is. A solid bug report can save us a lot of time instead of having to research everything on our own -> add full names & ids (best case scenario would be a wowhead.com link) of quests, npcs and so on.
Warlock CD Dark Soul increases crit/haste/mastery by 30% but the buff only says increases mastery/haste/crit by 30.

**To Reproduce**
Steps to reproduce the behavior: Play lock, pop dark soul, watch your buff and youll see % sign missing
Location N/(A
Name, Type N/A
Problem Description Buff
How it should work Should be a % sign in the buff

**Screenshots**
Not needed
**Additional context**

**Comment by vertria** [comment]
umm?it gives stats properly.

**Comment by vertria** [comment]
for each spec it gives other stats

**Comment by TheRealRickle** [comment]
Never said it doesn't give stats properly, just that the % sign is missing

**Comment by Greymane** [comment]
DBC data issue, requires clientside patching to fix, will be done when we have our CDN.
