### ISSUE TITLE
Quest Hellscream's Gift

### ISSUE THREAD

**Issue by TornroosV** [Damieninabox/Lotus-WoW-Bugtracker#52]
**Describe the bug**
https://www.wowhead.com/quest=31014/hellscreams-gift This quest has a bugged Quest marker on the map. Shows it being outside the brawlers guild when it should be inside Grommash hold

**To Reproduce**
Steps to reproduce the behavior: Level a Panda and chose Horde faction
Orgrimmar
Hemmscream's Gift, Quest
Problem Description
Quest marker is currently at 69.89, 32.17 in Orgrimmar
How it should work
Quest marker should be around 48.49, 71.25 In orgrimmar
**Screenshots**
https://imgur.com/a/7mWIlxw

**Comment by Damieninabox** [comment]
Fixed
