### ISSUE TITLE
Quest The Horde Way

### ISSUE THREAD

**Issue by TornroosV** [Damieninabox/Lotus-WoW-Bugtracker#54]
**Describe the bug**
Multiple issues here. Quest marker is in the wrong place, should be outside Brawlers guild but is in fact in Grommash Hold. Also cant see Garrosh outside brawlers guild due to phasing issue. https://www.wowhead.com/quest=31013/the-horde-way

**To Reproduce**
Steps to reproduce the behavior: Level a Panda and chose Horde Faction
Orgrimmar
The Horde Way, Quest
Problem Description
Player or NPC is in wrong phase so cannot interact to complete Quest, The quest marker is also in the wrong place showing the quest is in Grommash hold when it is infact outside the Brawlers guild in Orgrimmar
How it should work
Garrosh should walk outside Grommash Hold, Mount up on his Dragon mount and fly to Valley of Honor outside the Brawlers guild then dismount, the player should then be able to see him standing there and be able to turn his quest.
**Screenshots**
No screenshot but a video of how it works on retail https://www.youtube.com/watch?v=c6Fz3CqGMyk

**Additional context**
Ji firepaw should also be following the player as he travels from Grommash hold to Valley of Honor.

**Comment by BottledFart** [comment]
Duplicate

**Comment by Damieninabox** [comment]
Fixed with next update
