### ISSUE TITLE
[Raid] Elegon[60410]

### ISSUE THREAD

**Issue by herodope** [Damieninabox/Lotus-WoW-Bugtracker#57]
In phase 2 of the encounter with Elegon[60410] his pillars that create walls of lightning facing outwards were incorrectly facing inwards.

We actually had a few pulls on Elegon where this occurred, but it was changing. The first pull half of the room was facing in and half was facing out, then then following pulls they were all facing in. Unfortunately I did not get a screenshot of this, but a GM ported into our encounter towards the end and said he had took a quick video of the final moments of our encounter.

We had an additional issue with Elegon where he fell through the floor inbetween a few wipes. We could use Death and Decay or any AOE spell in the center of his platform to engage and begin the encounter, he would wait a few seconds attacking people at random, then walk up through the floor. We're not sure how we caused this, maybe if you wipe by having everyone jump into the center and the boss spawns before the floor recreates.

![image](https://user-images.githubusercontent.com/12160728/144713941-b13670ad-2ebf-44a3-8d08-307c61c4867b.png)

![image](https://user-images.githubusercontent.com/12160728/144713949-adf02efe-9526-4919-9dbc-c091d5df0c73.png)

**Comment by GMPeitho** [comment]
Pillars should be facing towards the walls, instead were facing inwards. 
![image](https://user-images.githubusercontent.com/95537492/144714862-1d5de3a6-9641-4566-905a-9593078a05cc.png)

**Comment by javialesm** [comment]
Currently, after Stage one ends, Elegon moves a little bit from the center of the platform. He should be alwails in the center of the platform.

![WoWScrnShot_120421_183045](https://user-images.githubusercontent.com/58116674/144728856-661a8b05-c7b4-4128-8c1f-6795e31ca605.jpg)

Also at the final phase the Radiating Energies (https://www.wowhead.com/spell=118313/radiating-energies?dd=3) aren't in their correct position as seen in the next image. It should be centered around the platform.

![Sin títuloo](https://user-images.githubusercontent.com/58116674/144729009-05e34767-84d5-4c2d-83ca-8715419e8536.png)

It should look like this

![image](https://user-images.githubusercontent.com/58116674/144729021-90b78683-5db8-444a-ba95-a02062a74e8a.png)

**Comment by Damieninabox** [comment]
@Greymane to reproduce the wipe issue, make sure to die properly against the boss, release spirit, go back in and once it loads his Grid, he will fall under the map

**Comment by Greymane** [comment]
@Topen01 wasn't able to reproduce the radiating energies issue, but i assume it is linked with the "decenter" bug, since elegon is the source of this spellcast
