### ISSUE TITLE
Badlands: Oversaturation of visual effects in Scar of the Worldbreaker leads to massively reduced framerate

### ISSUE THREAD

**Issue by Joncee** [Damieninabox/Lotus-WoW-Bugtracker#58]
**Describe the bug**
The stone fall environmental effects located in Scar of the Worldbreaker, in the Badlands, are duplicated several times over in each instance, and causes severe framerate and processing issues when withing the player's field of view.

**To Reproduce**
1- Locate and proceed down the Scar of the Worldbreaker section of the Badlands zone
2- Look for rockslide environmental effects

_Problem Description_: The rockslide environmental appears to trigger much too often, and without the previous effect ending, which causes visual processing bloat and framerate drop

_How it should work_: Each instance of the environmental effect should only be triggered when attacked by the elementals roaming the Scar, and only during the "The Day Deathwing Came" quest when the player is reliving Deathwing's arrival through unreliable narrators

**Screenshots**
Screenshot 1: Ground level view, framerate is noticeably lowered from processing extra effects

![Scar 1](https://user-images.githubusercontent.com/95506520/144714356-098c2d04-84e8-4300-84e0-8e816f13faa9.PNG)

Screenshot 2: Aerial view of those rockslides within field of vision. The framerate is much worse seen from this vantage point, likely given the number of visible instances compared to the ground level.

![Scar 2](https://user-images.githubusercontent.com/95506520/144714396-6eea3a55-8498-4048-b352-fbffe3c30bf2.PNG)

**Comment by Damieninabox** [comment]
Removed the visual effects for now, will come back to reworking the entire badlands, closing it for you
