### ISSUE TITLE
Badlands: Quest 'The Warden's Game' steps are out of order

### ISSUE THREAD

**Issue by Joncee** [Damieninabox/Lotus-WoW-Bugtracker#59]
**Describe the bug**
The stone constructs located in the Tomb of the Watcher, in the Badlands, can be interacted with despite not having completed prior steps in the quest chain.

**To Reproduce**

1- Locate the Sentinel and Warden NPCs in The Watcher's Tomb
2- Interact with NPCs to be offered a dialogue option

_Problem Description_: NPC dialogue option allows the player to activate them by inserting the associated 'pawn' quest item, despite the player having made no progress along the quest chain nor holding said quest item in inventory.

_How it should work_: Construct NPCs should be inert when interacted with prior to having reached that step in the quest line. Additionally, it should not be possible to fight the NPCs before having completed the puzzles located in the Tomb of the Watcher.

**Screenshots**

![Watcher 1](https://user-images.githubusercontent.com/95506520/144714849-740b6fb9-179e-4b94-9093-88ee2b828fef.png)

**Comment by Damieninabox** [comment]
Fixed with next server update, also added proper conditions
