### ISSUE TITLE
The Way Of The Tushui | Panda starting

### ISSUE THREAD

**Issue by BottledFart** [Damieninabox/Lotus-WoW-Bugtracker#6]
**Describe the bug**
Mobs don't attack when Aysa Cloudsinger is doing her thing.
**To Reproduce**
Take the quest, run to the cave and watch her do her thing.
The mobs will spawn, but just stand at the entrance.
It might be due to them being 3 levels under.
For reference: https://www.youtube.com/watch?v=5YaParKMTKQ&ab_channel=GitGudGuides
**Screenshots**
![image](https://user-images.githubusercontent.com/24526201/144665124-8c8d1d18-6ed5-4597-814b-3f5d5db2e4d0.png)

**Additional context**

**Comment by hamyhamz** [comment]
Also the NPC [Master Li Fei](https://www.wowhead.com/npc=54856/master-li-fei#objective-of) should be a friendly NPC according to this [video](https://www.youtube.com/watch?v=5YaParKMTKQ) while completing this quest. But as can be seen on screenshot, he was neutral and attackable.

![WoWScrnShot_120621_200601](https://user-images.githubusercontent.com/30901696/144907404-99bf0d5c-addb-4116-916a-77d45cee3b96.jpg)

**Comment by Damieninabox** [comment]
Fixed with next server update (could still be related to the player "outleveling" the creatures), kinda experimental
