### ISSUE TITLE
Guild issues

### ISSUE THREAD

**Issue by illogicalaction** [Damieninabox/Lotus-WoW-Bugtracker#61]
**Describe the bug**
Guild has some issue that if any members of the guild logout, they will be kicked from the guild, and( i still don't know the reason why) sometimes it keeps spamming [Guildmember name] has gone offline. [Guildmember name] has come online.
**To Reproduce**
Make a guild with 4-5 members or more.
Location N/A
Name N/A 
Type N/A
How it should work: You shouldn't be kicked from the guild if you logout, and the spam of <has gone offline.> <has come online> shouldn't also happen

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Anakia69** [comment]
Dupplicate from https://github.com/Damieninabox/Lotus-WoW-Bugtracker/issues/9#issue-1070916939
