### ISSUE TITLE
Jade forest mobs hitting too hard

### ISSUE THREAD

**Issue by TheRealRickle** [Damieninabox/Lotus-WoW-Bugtracker#62]
**Describe the bug**
A clear and concise description of what the bug is. A solid bug report can save us a lot of time instead of having to research everything on our own -> add full names & ids (best case scenario would be a wowhead.com link) of quests, npcs and so on.
Mobs in Thunder Hold hit way too hard
**To Reproduce**
Steps to reproduce the behavior: Go to thunder hold in jade forest and try
Location
Name, Type
Problem Description
How it should work They shouldn't hit nearly this hard, unsure how hard though

**Screenshots**
N/A
**Additional context**

**Comment by Damieninabox** [comment]
Please make sure to send us proper reports.

Name of the npc would help a lot

**Comment by TheRealRickle** [comment]
Currently the majority of mobs in the jade forest is hitting way too hard, I'll try to write down a list of all the mobs I've encountered

**Comment by Damieninabox** [comment]
Thanks
This will save us a lot of time :)

**Comment by TheRealRickle** [comment]
Thus far, I've found these: 
Strongarm Lieutenant
Strongarm Privates dont attack people who unless themselves attacked
Morgus Grimhatchet
Sha-infested Prowler
Strongarm Laborer
Stromarm Ace
Strongarm Gyrocopter (Don't think these are supposed to attack you at all)
Gyro-Mechanic Lavenderp
Master Engineer Cogswing
Corporal Jackson Silver
Captain Doren
Morgrinn Crackfang
Thunder Hold Cannoneer
Thunder hold Laborer
Thunder hold Mender
Siftworm

that all hit way too hard

**Comment by Damieninabox** [comment]
Damage ajusted
