### ISSUE TITLE
Quest | An Ancient Enemy (troll starting area)

### ISSUE THREAD

**Issue by SasquatchFiesta** [Damieninabox/Lotus-WoW-Bugtracker#7]
**Describe the bug**
was able to talk to Vol'jin for the first part, but he got stuck before engaging Zar'jira. Dropped quest to try again, still frozen infront of Zar'jira.

**To Reproduce**
Accepted An Ancient Enemy, Talked to Vol'jin, waited for his dialog to finish, just before he would engage with Zar'jira he froze.

**Comment by Damieninabox** [comment]
Fixed with next server update
