### ISSUE TITLE
Quest progress not shared in groups

### ISSUE THREAD

**Issue by TheRealRickle** [Damieninabox/Lotus-WoW-Bugtracker#70]
**Describe the bug**

While questing in the jade forest me and a friend noticed that ONLY mob kill quests were shared. Literally any other quest objective didn't share. We also tried several quests in valley of the four winds and again only kill quests shared.

**To Reproduce**
Group up and do some quests in the jade forest and valley of the four winds

Location Pandaria

Name, Type

Problem Description

How it should work 
We should share quest progress for the quests that don't involve looting items

**Screenshots**

**Additional context**

**Comment by Damieninabox** [comment]
Need further details, quest names, ids etc.
