### ISSUE TITLE
Quest: Life of the Party

### ISSUE THREAD

**Issue by Ladrood** [Damieninabox/Lotus-WoW-Bugtracker#71]
**Describe the bug**
A clear and concise description of what the bug is. A solid bug report can save us a lot of time instead of having to research everything on our own -> add full names & ids (best case scenario would be a wowhead.com link) of quests, npcs and so on.

You get the quest from Sassy Hardwrench, and you have to put on Awesome Party Ensemble.  It doesnt appear in bags like it should.  Cant do the quest, so therefore cant proceed with goblin leveling area.

**To Reproduce**
Location
Name, Type
Problem Description
How it should work

**Screenshots**

**Additional context**

**Comment by Damieninabox** [comment]
Fixed
