### ISSUE TITLE
Badlands: Quest "The Egg Lives On" can be completed before starting the chain

### ISSUE THREAD

**Issue by Joncee** [Damieninabox/Lotus-WoW-Bugtracker#72]
**Describe the bug**
The final step of the Badlands quest chain that starts with "A Strange Request" can be completed and the associated reward received before having picked up the seed quest or completed the necessary previous steps.

**To Reproduce**

1- Locate Doctor Blam at his camp in the Badlands
2- Interact with the NPC to be offered a choice of turning the quest in. The greyed out '?' doesn't prevent the player from selecting the dialogue option and allows one to complete the quest.

_Problem Description_: The greyed out '?' doesn't prevent the player from selecting the dialogue option and allows one to complete the quest without having participated in the necessary previous steps of the quest.

_How it should work_: Several steps ought to be required before arriving to the final reward of the quest chain, and the quest shouldn't be possible to complete and turn-in without the player being in possession of the required quest item.

**Screenshots**

![Blam](https://user-images.githubusercontent.com/95506520/144721482-545aecd4-e123-4acd-9681-0323a2f303f5.png)

**Additional context**

It also appears that the turret defense step of that same questline is available to anyone, regardless of whether the quest chain has been initiated. The player will be able to mount one of the cannons, which will cause Trogg waves to begin as per the quest.

**Comment by Damieninabox** [comment]
Fixed quest chain -> quest has no required item, regarding retail videos, you can just turn it on as you accept it
