### ISSUE TITLE
Loch Modan: Quest "Heartfelt Appreciation" can be turned-in without performing previous steps

### ISSUE THREAD

**Issue by Joncee** [Damieninabox/Lotus-WoW-Bugtracker#76]
**Describe the bug**
The final step of the hidden quest to find the Explorers' League Documents strewn across the zone can be turned in before the player has found the first document.

**To Reproduce**

1- Travel to Thelsamar, in Loch modan, and enter the Explorer's League headquarters
2- Locate Torren Squarejaw on the lower floor of the building and interact with the NPC to be given a dialogue option to turn the quest in and receive associated rewards

_Problem Description_: It is currently possible for a player to turn-in the last quest of the chain without having performed the previous steps that lead to it.

_How it should work_: The player should be required to find the six missing documents about the zone and bring them in, before being allowed to claim the reward for the task.

**Screenshots**

Screenshot 1:

![Torren](https://user-images.githubusercontent.com/95506520/144722240-37ded848-3a51-4ea9-ac35-a5dc3d9a6dad.png)

Screenshot 2: The documents can still be interacted with, despite having turned the final quest step in to the NPC

![Document](https://user-images.githubusercontent.com/95506520/144722328-b518129c-4c0d-44c8-9f96-ac1d9a2c663a.png)

**Comment by Damieninabox** [comment]
Fixed with next server update
