### ISSUE TITLE
[Raid] The Spirit Kings

### ISSUE THREAD

**Issue by herodope** [Damieninabox/Lotus-WoW-Bugtracker#77]
Issue: During encounter The Spirit Kings, specifically on boss Zian of the Endless Shadow[60701], his ability Undying Shadows[117506] is summoning an add Undying Shadow[60731] that isn't immune to fear. You can spam fear the add and ignore it.

Reproduction:
1) Engage The Spirit Kings encounter
2) When Zian the Endless Shadow phase begins, wait for boss to cast Endless Shadow[60701]
3) Fear the add Undying Shadow[60731] 

Review the immunity flags of NPC Undying Shadow[60731] to fix the issue.

**Comment by Damieninabox** [comment]
Fixed with next update
