### ISSUE TITLE
[Dungeon] Raigonn [56877]

### ISSUE THREAD

**Issue by herodope** [Damieninabox/Lotus-WoW-Bugtracker#78]
Issue: Raigonn [56877] the final boss of Gate of the Setting Sun has a Weak Spot[56895] NPC attached to it. The hitbox of the Weak Spot[56895]  is entirely too large and can be easily hit from the ground. The hitbox of the Weak Spot should not be able to be hit from anywhere except when you jump up onto Raigonn by using the objects in the room after he charges the wall. Currently the encounter is not functioning properly.

**Comment by Damieninabox** [comment]
Duplicate
