### ISSUE TITLE
Quest | The Source of our Livelihoods

### ISSUE THREAD

**Issue by RemoteDefinition** [Damieninabox/Lotus-WoW-Bugtracker#8]
**Describe the bug**
Pandaren Race Questline.

You receive the quest from Aysa Cloudsinger to board the cart to go the next village in need of help. When you arrive to the destination where the cart should be, the cart isn't there. Since the cart isn't there you will not be able to continue the pandaren storyline due to not receiving quest credit from boarding the cart.

Seems to be an issue with phasing with some oversight and help from Zephyr.

**To Reproduce**
In between the Singing Pools and Dai-Lo Farms in the Wandering Isles. More so closer to the Singing Pools. Head towards the cart driver and if there isn't any cart the quest is busted.

**Screenshots**
None but if need of any more evidence then ask Zephyr, the attending GM who helped.

**Comment by Damieninabox** [comment]
Duplicate
