### ISSUE TITLE
[NPC] Armored Battleboar displays incorrect behavior color

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#81]
**Describe the bug**
Armored Battleboars 36696 display incorrect the incorrect behavior color, showing up as aggressive (red). Nameplates, however, display correctly as yellow (neutral), same with mouseover.

**To Reproduce**
Steps to reproduce the behavior: Ensure NPC names are turned on
Location: Mulgore
Armored Battleboar, Beast

How it should work:
Creature should show up yellow in text like any creature that does not display aggressive behavior towards players and hostile factions.

**Screenshots**
https://imgur.com/a/i2LgIQd

Kind regards,

**Comment by Damieninabox** [comment]
Fixed with the next restart
