### ISSUE TITLE
[Quest] Consecrated Note missing quest tracker info

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#82]
**Describe the bug**
Said quest 27015 is missing quest tracker information for the expanded map

**To Reproduce**
Location: Mulgore
How it should work: Should point to Sunwalker Helaku in Camp Narache

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Damieninabox** [comment]
Fixed with next server update, make sure to delete your cache folder while your client is closed
