### ISSUE TITLE
[NPC] Prairie Wolf (2958) name not updating on creature death

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#83]
**Describe the bug**
Creature's display name remains red (or yellow, depending on behavior), even if dead.

**To Reproduce**
Steps to reproduce the behavior: .kill the NPC in question.
Location: Mulgore

How it should work: Creature's display name should turn grey to indicate a dead state.

**Screenshots**
https://imgur.com/a/IdNjTaP

**Additional context**
Applies to every entry for the creature

**Comment by Damieninabox** [comment]
Fixed with next restart
