### ISSUE TITLE
[NPC] Palemane creature entries missing

### ISSUE THREAD

**Issue by Gubbyfishy** [Damieninabox/Lotus-WoW-Bugtracker#85]
**Describe the bug**
Some creature entries are missing in a camp spot in Mulgore. Refer to the screenshot for the entries in question (note that this displays for Tanner only).

Affected NPCs:
https://www.wowhead.com/npc=2949/palemane-tanner#map
https://www.wowhead.com/npc=2951/palemane-poacher
https://www.wowhead.com/npc=2950/palemane-skinner

**To Reproduce**
Location: Mulgore

**Screenshots**
https://imgur.com/a/nvduhHQ

Kind regards,

**Comment by Damieninabox** [comment]
Adjusted with next server update
