### ISSUE TITLE
MSV Raid report.

### ISSUE THREAD

**Issue by Naytan96** [Damieninabox/Lotus-WoW-Bugtracker#86]
Raid
summons get ported to checkpoint not to summon location
Boss 1 - The dog on the far left would sometimes despawn if the boss was pulled and no one was close. Tuning wise was fine
Boss 2 - The crystals would cause line of sight issues and not despawn once picked up. shroud of reversal did not seem to work, although will be doing further testing. Sometimes shroud of reversal crystal didn't respawn after wiping. Tuning was fine
Boss 3 - Sometimes a DPS would get the tank mechanic and be ported inside for the tank add. Stacks from doing inside correctly were not being correctly applied for self heals. Tuning felt a little under.
Boss 4 - Meng would sometimes walk outside of the arena during one of his casts where he wonders around. Also maddening shout would sometimes not return players to be friendly with each other acting as enemy players but becoming invalid targets for buffs/healing/targeting. Tuning felt fine
Boss 5 - Would respawn and fall through the floor. Adds seem to be doing a rather large amount of damage (unsure if overscaled or correct) Tuning wise, i think the orbs have a bit too much hp but everything else was fine.
Boss 6 - seems incredibly undertuned. The combo would just hit you even if you were in the correct place. the ability that you get for completing the combo correctly would sometimes be able to be cast twice, cast regardless of being hit by a co

**Comment by Damieninabox** [comment]
Fixed on the live server
