### ISSUE TITLE
Quest Wretched Ringleader in Eversong Woods

### ISSUE THREAD

**Issue by Ladrood** [Damieninabox/Lotus-WoW-Bugtracker#88]
**Describe the bug**
A clear and concise description of what the bug is. A solid bug report can save us a lot of time instead of having to research everything on our own -> add full names & ids (best case scenario would be a wowhead.com link) of quests, npcs and so on.

Need to kill Aldaron the Reckless...the NPC is spawned but its completely out of LOS.  Cannot damage him to kill to gather his head for the quest. 

**To Reproduce**
Location
Name, Type
Problem Description
How it should work

Eversong Woods
Aldaron the Reckless
NPC out of LOS
kill him

**Screenshots**

**Additional context**

**Comment by Damieninabox** [comment]
Adjusted with next server update
