### ISSUE TITLE
Quest: The Fallen Courier

### ISSUE THREAD

**Issue by Ladrood** [Damieninabox/Lotus-WoW-Bugtracker#89]
**Describe the bug**
A clear and concise description of what the bug is. A solid bug report can save us a lot of time instead of having to research everything on our own -> add full names & ids (best case scenario would be a wowhead.com link) of quests, npcs and so on.

You are suppose to be able to loot 4 blood samples from cats and bats.  I killed them twice over, over 36 kills and not one sample drop. 

**To Reproduce**
Location
Name, Type
Problem Description
How it should work

Ghostlands

**Screenshots**

**Additional context**

**Comment by Damieninabox** [comment]
Fixed with next server update
