### ISSUE TITLE
Misc - Guild | I get removed from my guild each time I logout

### ISSUE THREAD

**Issue by Anakia69** [Damieninabox/Lotus-WoW-Bugtracker#9]
**Describe the bug**

Each time I logout, I think I am being auto removed from my guild.

**To Reproduce**

N/C

**Screenshots**

![image](https://user-images.githubusercontent.com/95502789/144665711-8f121616-570d-4789-925f-409de551d268.png)

Edit. Created a second warrior to check things out. I'm still a member of the guild, but when I'm playing on my warrior I can't see it (see first screen)

![image](https://user-images.githubusercontent.com/95502789/144667707-3ddb6586-a205-4f68-9427-7d155d71f865.png)

**Additional context**

Guild Name : Eternal Symphonia
Char Name : Reichu

I created this guild & my char on the first beta. Perhaps, the bug would not occur on new characters. I still see the guild chat though.
This issue already happened to me during the first beta, so perhaps there's something wrong with my char ?

**Comment by SasquatchFiesta** [comment]
Had this same issue, I was the Guild Leader and other members saw me in guild. I was able to be re-invited, but now I'm an Initiate and we don't have anyone in the Guild Leader rank. 
![image](https://user-images.githubusercontent.com/45911989/144692221-f23064f2-937b-433a-92a6-35d49330a78f.png)

**Comment by herodope** [comment]
+1 guild < asdf > had this same issue. Two users specifically were having issues in a guild of ~12 characters at the time of writing this post. Solofro and Antisxoxo were the character names who were being removed on logout. will attempt to look for any other additional reproduce steps

**Comment by Anakia69** [comment]
The bug is happening to one of my guildie aswell. New character from second beta. Weird :s

**Comment by Greymane** [comment]
Need a proper way to reproduce it, no luck so far :/

**Comment by SasquatchFiesta** [comment]
> Need a proper way to reproduce it, no luck so far :/

I have this issue every time I relog after joining a guild (just tested with another guild aswell). I'd be happy to give you my account info if it helps you reproduce it, Taffy#2596 on discord, Taff or Taffy in game (happens with both characters consistently, other characters don't seem to have the issue). If you can just take it over go ahead or have a mod/dev DM me in discord for info.

![image](https://user-images.githubusercontent.com/45911989/145105284-24456737-396e-43f7-9ef1-79a78748e0ee.png)

![image](https://user-images.githubusercontent.com/45911989/145105399-e39bbab8-cf0f-4330-b1e6-fe34d2af4d25.png)

**Comment by Greymane** [comment]
> 

ill ask the owner for a pdump of you character, should be enough, thanks.
