### ISSUE TITLE
LOS casting mobs

### ISSUE THREAD

**Issue by Yalinar** [Damieninabox/Lotus-WoW-Bugtracker#93]
**Describe the bug**
If u LOS a Castermnob, they often stand in place and dont do anything.

**To Reproduce**
Steps to reproduce the behavior: Aggro a Castermob and run out of line of sight.
Location: multiple Dungeonmobs while grinding lvl. 20-50 Dungeons.
Problem Description: They just stand in place not doing anything.
How it should work: They should stop casting and run to you.

**Comment by Damieninabox** [comment]
If you run into this issue, make sure to write down the proper Npc names.

Those are script issues, not an overall issue

**Comment by Damieninabox** [comment]
Will close it for now, since I don't expect an answer
