### ISSUE TITLE
Quest: Weed War

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#95]
**Describe the bug**
Bug: Gai-Lin has the quest trigger 'What Weeds' but it doesn't activate (see screenshot attached)
This bug is applicable to the following quests:
 
https://www.wowhead.com/quest=30052/weed-war

https://www.wowhead.com/quest=30321/weed-war-ii

**To Reproduce**
Obtain the quest from Ga-Lin or the Daily from Jogu the drunk
Location: Valley of the Four winds

**How it should work** 
Quest action should take place in co-ordinates 38.56, 51.73
Speaking to Gai-Lin should trigger the weed-whacking event which can be performed even while mounted

**Additional context** 
This quest is part of Tiller's quest chain
 
![Weed War Bug](https://user-images.githubusercontent.com/95563818/144739214-b12fe012-c6ca-4b30-b506-d3a87d69182f.PNG)

**Comment by Damieninabox** [comment]
Fixed with next core update
