### ISSUE TITLE
Quest: Money Matters (missing NPC towards quest completion)

### ISSUE THREAD

**Issue by BanHammer69** [Damieninabox/Lotus-WoW-Bugtracker#99]
https://www.wowhead.com/quest=30322/money-matters

**Bug** Unable to locate NPC Trader Jambeezi for quest completion. 

The other 3 required NPCs had white speech bubbles on minimap to indicate that they were part of the quest and interacting with them gave you quest completion steps
![Money Matter Bug](https://user-images.githubusercontent.com/95563818/144741853-d6af53f2-0ee2-44a4-aac8-ff6c3aa1d2d9.PNG)
.

**Comment by Damieninabox** [comment]
Fixed with next server restart -> also fully erased previous scripts and properly scripted the quest
